//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: bigmap_common.proto
namespace map
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TerrainData")]
  public partial class TerrainData : global::ProtoBuf.IExtensible
  {
    public TerrainData() {}
    
    private map.TerrainType __terrainType = map.TerrainType.kBlock;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"_terrainType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(map.TerrainType.kBlock)]
    public map.TerrainType _terrainType
    {
      get { return __terrainType; }
      set { __terrainType = value; }
    }
    private map.PrefabType __prefabType = map.PrefabType.kBlank;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"_prefabType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(map.PrefabType.kBlank)]
    public map.PrefabType _prefabType
    {
      get { return __prefabType; }
      set { __prefabType = value; }
    }
    private uint __watchTowerLevel = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"_watchTowerLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint _watchTowerLevel
    {
      get { return __watchTowerLevel; }
      set { __watchTowerLevel = value; }
    }
    private int __groupID = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"_groupID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int _groupID
    {
      get { return __groupID; }
      set { __groupID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HexCoord")]
  public partial class HexCoord : global::ProtoBuf.IExtensible
  {
    public HexCoord() {}
    
    private int _q = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"q", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int q
    {
      get { return _q; }
      set { _q = value; }
    }
    private int _r = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"r", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int r
    {
      get { return _r; }
      set { _r = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterZoon")]
  public partial class MonsterZoon : global::ProtoBuf.IExtensible
  {
    public MonsterZoon() {}
    
    private map.HexCoord __coord = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"_coord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public map.HexCoord _coord
    {
      get { return __coord; }
      set { __coord = value; }
    }
    private int __monsterTypeID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"_monsterTypeID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int _monsterTypeID
    {
      get { return __monsterTypeID; }
      set { __monsterTypeID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildZoon")]
  public partial class BuildZoon : global::ProtoBuf.IExtensible
  {
    public BuildZoon() {}
    
    private map.HexCoord __coord = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"_coord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public map.HexCoord _coord
    {
      get { return __coord; }
      set { __coord = value; }
    }
    private int __buildingTypeID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"_buildingTypeID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int _buildingTypeID
    {
      get { return __buildingTypeID; }
      set { __buildingTypeID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WatchGroupProp")]
  public partial class WatchGroupProp : global::ProtoBuf.IExtensible
  {
    public WatchGroupProp() {}
    
    private int __money = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"_money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int _money
    {
      get { return __money; }
      set { __money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BigMapSerializable")]
  public partial class BigMapSerializable : global::ProtoBuf.IExtensible
  {
    public BigMapSerializable() {}
    
    private int _m_nVersion = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"m_nVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int m_nVersion
    {
      get { return _m_nVersion; }
      set { _m_nVersion = value; }
    }
    private readonly global::System.Collections.Generic.List<map.TerrainData> _m_TerrainDatas = new global::System.Collections.Generic.List<map.TerrainData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"m_TerrainDatas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<map.TerrainData> m_TerrainDatas
    {
      get { return _m_TerrainDatas; }
    }
  
    private int _m_nMapWidth = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"m_nMapWidth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int m_nMapWidth
    {
      get { return _m_nMapWidth; }
      set { _m_nMapWidth = value; }
    }
    private readonly global::System.Collections.Generic.List<map.MonsterZoon> _m_Monsters = new global::System.Collections.Generic.List<map.MonsterZoon>();
    [global::ProtoBuf.ProtoMember(4, Name=@"m_Monsters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<map.MonsterZoon> m_Monsters
    {
      get { return _m_Monsters; }
    }
  
    private readonly global::System.Collections.Generic.List<map.BuildZoon> _m_buildings = new global::System.Collections.Generic.List<map.BuildZoon>();
    [global::ProtoBuf.ProtoMember(5, Name=@"m_buildings", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<map.BuildZoon> m_buildings
    {
      get { return _m_buildings; }
    }
  
    private readonly global::System.Collections.Generic.List<map.BuildZoon> _m_prefabBuilidings = new global::System.Collections.Generic.List<map.BuildZoon>();
    [global::ProtoBuf.ProtoMember(6, Name=@"m_prefabBuilidings", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<map.BuildZoon> m_prefabBuilidings
    {
      get { return _m_prefabBuilidings; }
    }
  
    private readonly global::System.Collections.Generic.List<map.WatchGroupProp> _m_watchGroups = new global::System.Collections.Generic.List<map.WatchGroupProp>();
    [global::ProtoBuf.ProtoMember(7, Name=@"m_watchGroups", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<map.WatchGroupProp> m_watchGroups
    {
      get { return _m_watchGroups; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _m_watchGroupLengths = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"m_watchGroupLengths", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> m_watchGroupLengths
    {
      get { return _m_watchGroupLengths; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TerrainType")]
    public enum TerrainType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBlock", Value=0)]
      kBlock = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kGrassField", Value=1)]
      kGrassField = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kSnowField", Value=2)]
      kSnowField = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kSandField", Value=3)]
      kSandField = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kOldBattle", Value=4)]
      kOldBattle = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kForestFiled", Value=5)]
      kForestFiled = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kSkyIland", Value=6)]
      kSkyIland = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlane", Value=7)]
      kPlane = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PrefabType")]
    public enum PrefabType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBlank", Value=0)]
      kBlank = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLord", Value=1)]
      kLord = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEnemy", Value=2)]
      kEnemy = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"OccupyType")]
    public enum OccupyType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEmpty", Value=0)]
      kEmpty = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPrefabBuilding", Value=1)]
      kPrefabBuilding = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBuilding", Value=2)]
      kBuilding = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kUniter", Value=3)]
      kUniter = 3
    }
  
}