//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: error_code.proto
namespace error_code
{
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcSuccess", Value=0)]
      kEcSuccess = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGeneralNullPointer", Value=101)]
      kEcGeneralNullPointer = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGeneralConfigError", Value=102)]
      kEcGeneralConfigError = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGeneralInvalidParameter", Value=103)]
      kEcGeneralInvalidParameter = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGeneralDbError", Value=104)]
      kEcGeneralDbError = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGeneralDbStopService", Value=105)]
      kEcGeneralDbStopService = 105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGeneralServiceNotReady", Value=106)]
      kEcGeneralServiceNotReady = 106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGeneralNotFoundPlayer", Value=107)]
      kEcGeneralNotFoundPlayer = 107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGeneralInvalidMessage", Value=108)]
      kEcGeneralInvalidMessage = 108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGeneralNotEnoughMoney", Value=109)]
      kEcGeneralNotEnoughMoney = 109,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECGeneralNotEnoughLumber", Value=110)]
      kECGeneralNotEnoughLumber = 110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECGeneralNotEnoughGem", Value=111)]
      kECGeneralNotEnoughGem = 111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECGeneralNotEnoughFood", Value=112)]
      kECGeneralNotEnoughFood = 112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGeneralFailedInAddMoney", Value=113)]
      kEcGeneralFailedInAddMoney = 113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGeneralFailedInAddLumber", Value=114)]
      kEcGeneralFailedInAddLumber = 114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGeneralFailedInAddGem", Value=115)]
      kEcGeneralFailedInAddGem = 115,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGeneralFailedInAddFood", Value=116)]
      kEcGeneralFailedInAddFood = 116,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECGeneralServerShutingdown", Value=117)]
      kECGeneralServerShutingdown = 117,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcLoginUnknown", Value=1000)]
      kEcLoginUnknown = 1000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcLoginUsStopService", Value=1001)]
      kEcLoginUsStopService = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcLoginNoFreeGs", Value=1002)]
      kEcLoginNoFreeGs = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcLoginNoFreeDb", Value=1003)]
      kEcLoginNoFreeDb = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcLoginMultiLogin", Value=1006)]
      kEcLoginMultiLogin = 1006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcLoginNoLoginInfo", Value=1007)]
      kEcLoginNoLoginInfo = 1007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcLoginInvalidStatus", Value=1008)]
      kEcLoginInvalidStatus = 1008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcLoginInvalidAccount", Value=1009)]
      kEcLoginInvalidAccount = 1009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcLoginInvalidSessionKey", Value=1010)]
      kEcLoginInvalidSessionKey = 1010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcLoginCreatePlayerFailure", Value=1011)]
      kEcLoginCreatePlayerFailure = 1011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECLoginSessionError", Value=1012)]
      kECLoginSessionError = 1012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECLoginSessionValidateFail", Value=1013)]
      kECLoginSessionValidateFail = 1013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECLoginPVEBattleLock", Value=1014)]
      kECLoginPVEBattleLock = 1014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcLoginLoadPlayerTimeOut", Value=1016)]
      kEcLoginLoadPlayerTimeOut = 1016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcLoginCacheIsDisable", Value=1017)]
      kEcLoginCacheIsDisable = 1017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcAddPlayerToCacheFailed", Value=1018)]
      kEcAddPlayerToCacheFailed = 1018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcLoginReloginKickOut", Value=1019)]
      kEcLoginReloginKickOut = 1019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcLoginGSProtect", Value=1020)]
      kEcLoginGSProtect = 1020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcAllcateGSServerNotReady", Value=1021)]
      kEcAllcateGSServerNotReady = 1021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcRemovePlayerTimeout", Value=1022)]
      kEcRemovePlayerTimeout = 1022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcPlayerRemoving", Value=1023)]
      kEcPlayerRemoving = 1023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcRemovePlayerNotFound", Value=1024)]
      kEcRemovePlayerNotFound = 1024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcUserNoPlayerId", Value=1050)]
      kEcUserNoPlayerId = 1050,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcUserNoAccount", Value=1051)]
      kEcUserNoAccount = 1051,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcUserUsStopService", Value=1052)]
      kEcUserUsStopService = 1052,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcPmInvalidCommand", Value=1100)]
      kEcPmInvalidCommand = 1100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcPmForbidden", Value=1101)]
      kEcPmForbidden = 1101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcPmInvalidModule", Value=1102)]
      kEcPmInvalidModule = 1102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcPmFailedUnkown", Value=1103)]
      kEcPmFailedUnkown = 1103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcNameError", Value=1150)]
      kEcNameError = 1150,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcTestTimeout", Value=1200)]
      kEcTestTimeout = 1200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcTestFailure", Value=1201)]
      kEcTestFailure = 1201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcTestContinue", Value=1202)]
      kEcTestContinue = 1202,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildAlreadyJoinGuild", Value=1300)]
      kEcGuildAlreadyJoinGuild = 1300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildNotJoinGuildYet", Value=1301)]
      kEcGuildNotJoinGuildYet = 1301,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildCreateGuildFailed", Value=1302)]
      kEcGuildCreateGuildFailed = 1302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildInvalidName", Value=1303)]
      kEcGuildInvalidName = 1303,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildNoPermission", Value=1304)]
      kEcGuildNoPermission = 1304,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildMasterQuitForbidden", Value=1305)]
      kEcGuildMasterQuitForbidden = 1305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildGuildNoExist", Value=1306)]
      kEcGuildGuildNoExist = 1306,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildGuildFull", Value=1307)]
      kEcGuildGuildFull = 1307,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildOverApplicationLimit", Value=1308)]
      kEcGuildOverApplicationLimit = 1308,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildUnderRequirement", Value=1309)]
      kEcGuildUnderRequirement = 1309,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildGuildJoinForbidden", Value=1310)]
      kEcGuildGuildJoinForbidden = 1310,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildRepeatApply", Value=1312)]
      kEcGuildRepeatApply = 1312,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildApplicantNoExist", Value=1313)]
      kEcGuildApplicantNoExist = 1313,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildMemberNoExist", Value=1314)]
      kEcGuildMemberNoExist = 1314,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildKickFailed", Value=1315)]
      kEcGuildKickFailed = 1315,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildPositionFull", Value=1316)]
      kEcGuildPositionFull = 1316,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildLowestPosition", Value=1317)]
      kEcGuildLowestPosition = 1317,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcGuildInvalidContent", Value=1318)]
      kEcGuildInvalidContent = 1318,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcMailUnknown", Value=1400)]
      kEcMailUnknown = 1400,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcMailNoReceiveId", Value=1401)]
      kEcMailNoReceiveId = 1401,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcMailNoMail", Value=1402)]
      kEcMailNoMail = 1402,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcMailBeenRead", Value=1403)]
      kEcMailBeenRead = 1403,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcMailSubjectTooLong", Value=1404)]
      kEcMailSubjectTooLong = 1404,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcMailContentTooLong", Value=1405)]
      kEcMailContentTooLong = 1405,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcMailNoAnnounce", Value=1406)]
      kEcMailNoAnnounce = 1406,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcMailSysAnnFilterTooLong", Value=1407)]
      kEcMailSysAnnFilterTooLong = 1407,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcMailUpdateBatchOverflow", Value=1408)]
      kEcMailUpdateBatchOverflow = 1408,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcMailBeenExtract", Value=1409)]
      kEcMailBeenExtract = 1409,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcMailErrorFlag", Value=1410)]
      kEcMailErrorFlag = 1410,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kEcMailNoResource", Value=1411)]
      kEcMailNoResource = 1411,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingUnknown", Value=1500)]
      kECBuildingUnknown = 1500,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingNoExist", Value=1501)]
      kECBuildingNoExist = 1501,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingInvalidPosition", Value=1502)]
      kECBuildingInvalidPosition = 1502,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingCastleLevelTooLow", Value=1503)]
      kECBuildingCastleLevelTooLow = 1503,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingPlayerLevelTooLow", Value=1504)]
      kECBuildingPlayerLevelTooLow = 1504,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingOverLimit", Value=1505)]
      kECBuildingOverLimit = 1505,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingWorkQueueFull", Value=1506)]
      kECBuildingWorkQueueFull = 1506,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingCanNotUpgrade", Value=1507)]
      kECBuildingCanNotUpgrade = 1507,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingUpgrading", Value=1508)]
      kECBuildingUpgrading = 1508,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingNoUpgrading", Value=1509)]
      kECBuildingNoUpgrading = 1509,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingInvalidStatus", Value=1510)]
      kECBuildingInvalidStatus = 1510,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingSameBuilding", Value=1511)]
      kECBuildingSameBuilding = 1511,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingRemovePrefeb", Value=1512)]
      kECBuildingRemovePrefeb = 1512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingMistNoExist", Value=1513)]
      kECBuildingMistNoExist = 1513,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingWatchTowerLowLevel", Value=1514)]
      kECBuildingWatchTowerLowLevel = 1514,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingMistAlreadyUnlocked", Value=1515)]
      kECBuildingMistAlreadyUnlocked = 1515,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingForbidBuild", Value=1516)]
      kECBuildingForbidBuild = 1516,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingRequirePrecedingMist", Value=1517)]
      kECBuildingRequirePrecedingMist = 1517,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingOutOfMap", Value=1518)]
      kECBuildingOutOfMap = 1518,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingAlreadyExist", Value=1519)]
      kECBuildingAlreadyExist = 1519,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingOverWorkQueueLimit", Value=1520)]
      kECBuildingOverWorkQueueLimit = 1520,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBuildingUnmovable", Value=1521)]
      kECBuildingUnmovable = 1521,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECDefenceUnkown", Value=1600)]
      kECDefenceUnkown = 1600,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECDefenceInvalidAmount", Value=1601)]
      kECDefenceInvalidAmount = 1601,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECDefenceInvalidCharacter", Value=1602)]
      kECDefenceInvalidCharacter = 1602,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECDefenceInvalidPosition", Value=1603)]
      kECDefenceInvalidPosition = 1603,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECDefenceInvalidData", Value=1604)]
      kECDefenceInvalidData = 1604,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECDefenceTooManyFormation", Value=1605)]
      kECDefenceTooManyFormation = 1605,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECEffectUnkown", Value=1700)]
      kECEffectUnkown = 1700,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECEffectInvalidAttributeType", Value=1701)]
      kECEffectInvalidAttributeType = 1701,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECEffectNoStoreCapacity", Value=1702)]
      kECEffectNoStoreCapacity = 1702,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBattleUnkown", Value=1800)]
      kECBattleUnkown = 1800,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBattleInvalidStatus", Value=1801)]
      kECBattleInvalidStatus = 1801,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBattleInvalidArmy", Value=1802)]
      kECBattleInvalidArmy = 1802,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBattleInvalidBattleId", Value=1803)]
      kECBattleInvalidBattleId = 1803,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBattleCreateRoomFailed", Value=1804)]
      kECBattleCreateRoomFailed = 1804,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBattleRoomNoExist", Value=1805)]
      kECBattleRoomNoExist = 1805,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBattleDifferenceFrameOverLimit", Value=1806)]
      kECBattleDifferenceFrameOverLimit = 1806,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBattleInvalidCommand", Value=1807)]
      kECBattleInvalidCommand = 1807,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBattleInvalidPlayerId", Value=1808)]
      kECBattleInvalidPlayerId = 1808,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECBattleDifferentVersion", Value=1809)]
      kECBattleDifferentVersion = 1809,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECHeroUnkown", Value=1900)]
      kECHeroUnkown = 1900,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECHeroNotFoundConfig", Value=1901)]
      kECHeroNotFoundConfig = 1901,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECHeroUnActive", Value=1902)]
      kECHeroUnActive = 1902,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECHeroOutMaxLevel", Value=1903)]
      kECHeroOutMaxLevel = 1903,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECHeroEquipFoundConfig", Value=1904)]
      kECHeroEquipFoundConfig = 1904,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECHeroMaxLevel", Value=1905)]
      kECHeroMaxLevel = 1905,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECHeroChipNotEnough", Value=1906)]
      kECHeroChipNotEnough = 1906,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECHeroHallLevelLimit", Value=1907)]
      kECHeroHallLevelLimit = 1907,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECHeroGoldNotEnough", Value=1908)]
      kECHeroGoldNotEnough = 1908,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECArenaUnkown", Value=2000)]
      kECArenaUnkown = 2000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECArenaRepeateApplied", Value=2001)]
      kECArenaRepeateApplied = 2001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECArenaServerOffline", Value=2002)]
      kECArenaServerOffline = 2002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECArenaInvalidChestIndex", Value=2003)]
      kECArenaInvalidChestIndex = 2003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECArenaInvalidChestStatus", Value=2004)]
      kECArenaInvalidChestStatus = 2004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECArenaChestQueueFull", Value=2005)]
      kECArenaChestQueueFull = 2005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECArenaNoMoreChestQueue", Value=2006)]
      kECArenaNoMoreChestQueue = 2006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECArenaInvalidLineup", Value=2007)]
      kECArenaInvalidLineup = 2007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECArenaCaravanEscorting", Value=2008)]
      kECArenaCaravanEscorting = 2008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECArenaCaravanRobing", Value=2009)]
      kECArenaCaravanRobing = 2009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECPVEUnkown", Value=2100)]
      kECPVEUnkown = 2100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECPVENotFoundViewTarget", Value=2101)]
      kECPVENotFoundViewTarget = 2101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECPVECreateViewPlayerError", Value=2102)]
      kECPVECreateViewPlayerError = 2102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECPVEAlreadyInViewStatus", Value=2103)]
      kECPVEAlreadyInViewStatus = 2103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECPVENotFoundEnemy", Value=2104)]
      kECPVENotFoundEnemy = 2104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECPVENotMatchEnemy", Value=2105)]
      kECPVENotMatchEnemy = 2105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECPVEUnkownEnemy", Value=2106)]
      kECPVEUnkownEnemy = 2106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECPVEAlreadyInBattle", Value=2107)]
      kECPVEAlreadyInBattle = 2107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECPVENotFoundPlayer", Value=2108)]
      kECPVENotFoundPlayer = 2108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECPVEPlayerAlreadyLock", Value=2109)]
      kECPVEPlayerAlreadyLock = 2109,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECPVEInitBattleFailed", Value=2110)]
      kECPVEInitBattleFailed = 2110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECPVERequestView", Value=2111)]
      kECPVERequestView = 2111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECCaravanUnkown", Value=2200)]
      kECCaravanUnkown = 2200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECCaravanEscorting", Value=2201)]
      kECCaravanEscorting = 2201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECCaravanStartEscortFailed", Value=2202)]
      kECCaravanStartEscortFailed = 2202,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECCaravanStillLock", Value=2203)]
      kECCaravanStillLock = 2203,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECCaravanInvalidCaravanId", Value=2204)]
      kECCaravanInvalidCaravanId = 2204,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECCaravanInvalidTarget", Value=2205)]
      kECCaravanInvalidTarget = 2205,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECCaravanBattling", Value=2206)]
      kECCaravanBattling = 2206,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECCaravanNotEscorting", Value=2207)]
      kECCaravanNotEscorting = 2207,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECCaravanTargetNotEscorting", Value=2208)]
      kECCaravanTargetNotEscorting = 2208,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECCaravanStartBattleFailed", Value=2209)]
      kECCaravanStartBattleFailed = 2209,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECCaravanCooldowning", Value=2210)]
      kECCaravanCooldowning = 2210,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECCaravanPVPApplying", Value=2211)]
      kECCaravanPVPApplying = 2211,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECCaravanRobing", Value=2212)]
      kECCaravanRobing = 2212,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECTransferBlockMsgFailed", Value=2300)]
      kECTransferBlockMsgFailed = 2300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kECTransferNotBlocking", Value=2301)]
      kECTransferNotBlocking = 2301
    }
  
}