//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: msgdefine_common_pt.proto
namespace protomsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NetAddress")]
  public partial class NetAddress : global::ProtoBuf.IExtensible
  {
    public NetAddress() {}
    
    private uint _port = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Resource")]
  public partial class Resource : global::ProtoBuf.IExtensible
  {
    public Resource() {}
    
    private uint _res_type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"res_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint res_type
    {
      get { return _res_type; }
      set { _res_type = value; }
    }
    private uint _sub_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sub_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sub_type
    {
      get { return _sub_type; }
      set { _sub_type = value; }
    }
    private ulong _value = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgMailInfo")]
  public partial class MsgMailInfo : global::ProtoBuf.IExtensible
  {
    public MsgMailInfo() {}
    
    private ulong _id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private ulong _sender_id = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sender_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong sender_id
    {
      get { return _sender_id; }
      set { _sender_id = value; }
    }
    private string _sender_name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sender_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sender_name
    {
      get { return _sender_name; }
      set { _sender_name = value; }
    }
    private ulong _receive_id = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"receive_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong receive_id
    {
      get { return _receive_id; }
      set { _receive_id = value; }
    }
    private string _receive_name = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"receive_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string receive_name
    {
      get { return _receive_name; }
      set { _receive_name = value; }
    }
    private string _subject = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"subject", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string subject
    {
      get { return _subject; }
      set { _subject = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private uint _read_flag = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"read_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint read_flag
    {
      get { return _read_flag; }
      set { _read_flag = value; }
    }
    private readonly global::System.Collections.Generic.List<protomsg.Resource> _res = new global::System.Collections.Generic.List<protomsg.Resource>();
    [global::ProtoBuf.ProtoMember(10, Name=@"res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protomsg.Resource> res
    {
      get { return _res; }
    }
  
    private long _end_time = default(long);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"end_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long end_time
    {
      get { return _end_time; }
      set { _end_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgClientMailInfo")]
  public partial class MsgClientMailInfo : global::ProtoBuf.IExtensible
  {
    public MsgClientMailInfo() {}
    
    private ulong _id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private ulong _sender_id = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sender_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong sender_id
    {
      get { return _sender_id; }
      set { _sender_id = value; }
    }
    private string _sender_name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sender_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sender_name
    {
      get { return _sender_name; }
      set { _sender_name = value; }
    }
    private string _subject = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"subject", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string subject
    {
      get { return _subject; }
      set { _subject = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private uint _read_flag = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"read_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint read_flag
    {
      get { return _read_flag; }
      set { _read_flag = value; }
    }
    private readonly global::System.Collections.Generic.List<protomsg.Resource> _res = new global::System.Collections.Generic.List<protomsg.Resource>();
    [global::ProtoBuf.ProtoMember(8, Name=@"res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protomsg.Resource> res
    {
      get { return _res; }
    }
  
    private long _end_time = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"end_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long end_time
    {
      get { return _end_time; }
      set { _end_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ApplicantData")]
  public partial class ApplicantData : global::ProtoBuf.IExtensible
  {
    public ApplicantData() {}
    
    private ulong _player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _head = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint head
    {
      get { return _head; }
      set { _head = value; }
    }
    private uint _cup = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"cup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cup
    {
      get { return _cup; }
      set { _cup = value; }
    }
    private uint _charge = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"charge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charge
    {
      get { return _charge; }
      set { _charge = value; }
    }
    private ulong _time = default(ulong);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _db_id = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"db_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint db_id
    {
      get { return _db_id; }
      set { _db_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildJoinCondition")]
  public partial class GuildJoinCondition : global::ProtoBuf.IExtensible
  {
    public GuildJoinCondition() {}
    
    private uint _require_cup = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"require_cup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint require_cup
    {
      get { return _require_cup; }
      set { _require_cup = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildMemberData")]
  public partial class GuildMemberData : global::ProtoBuf.IExtensible
  {
    public GuildMemberData() {}
    
    private ulong _player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _head = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint head
    {
      get { return _head; }
      set { _head = value; }
    }
    private uint _position = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint position
    {
      get { return _position; }
      set { _position = value; }
    }
    private uint _cup = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"cup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cup
    {
      get { return _cup; }
      set { _cup = value; }
    }
    private ulong _join_time = default(ulong);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"join_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong join_time
    {
      get { return _join_time; }
      set { _join_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildSearchRange")]
  public partial class GuildSearchRange : global::ProtoBuf.IExtensible
  {
    public GuildSearchRange() {}
    
    private uint _min_value = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"min_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint min_value
    {
      get { return _min_value; }
      set { _min_value = value; }
    }
    private uint _max_value = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"max_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_value
    {
      get { return _max_value; }
      set { _max_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildSearchCondition")]
  public partial class GuildSearchCondition : global::ProtoBuf.IExtensible
  {
    public GuildSearchCondition() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _language = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"language", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint language
    {
      get { return _language; }
      set { _language = value; }
    }
    private uint _join_type = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"join_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint join_type
    {
      get { return _join_type; }
      set { _join_type = value; }
    }
    private protomsg.GuildSearchRange _require_cup_range = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"require_cup_range", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protomsg.GuildSearchRange require_cup_range
    {
      get { return _require_cup_range; }
      set { _require_cup_range = value; }
    }
    private protomsg.GuildSearchRange _member_count_range = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"member_count_range", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protomsg.GuildSearchRange member_count_range
    {
      get { return _member_count_range; }
      set { _member_count_range = value; }
    }
    private uint _cup_range_id = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"cup_range_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cup_range_id
    {
      get { return _cup_range_id; }
      set { _cup_range_id = value; }
    }
    private uint _recommend_level = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"recommend_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint recommend_level
    {
      get { return _recommend_level; }
      set { _recommend_level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildBriefData")]
  public partial class GuildBriefData : global::ProtoBuf.IExtensible
  {
    public GuildBriefData() {}
    
    private ulong _guild_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guild_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guild_id
    {
      get { return _guild_id; }
      set { _guild_id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _icon = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private uint _join_type = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"join_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint join_type
    {
      get { return _join_type; }
      set { _join_type = value; }
    }
    private ulong _total_cup = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"total_cup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong total_cup
    {
      get { return _total_cup; }
      set { _total_cup = value; }
    }
    private uint _member_count = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"member_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint member_count
    {
      get { return _member_count; }
      set { _member_count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Coord")]
  public partial class Coord : global::ProtoBuf.IExtensible
  {
    public Coord() {}
    
    private int _x = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleTroop")]
  public partial class BattleTroop : global::ProtoBuf.IExtensible
  {
    public BattleTroop() {}
    
    private uint _unit_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"unit_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint unit_id
    {
      get { return _unit_id; }
      set { _unit_id = value; }
    }
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _amount = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _construction_type = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"construction_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint construction_type
    {
      get { return _construction_type; }
      set { _construction_type = value; }
    }
    private uint _index = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint index
    {
      get { return _index; }
      set { _index = value; }
    }
    private protomsg.Coord _pos = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protomsg.Coord pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private uint _equip_level = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"equip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint equip_level
    {
      get { return _equip_level; }
      set { _equip_level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleHero")]
  public partial class BattleHero : global::ProtoBuf.IExtensible
  {
    public BattleHero() {}
    
    private uint _unit_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"unit_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint unit_id
    {
      get { return _unit_id; }
      set { _unit_id = value; }
    }
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _amount = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint amount
    {
      get { return _amount; }
      set { _amount = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _equip_level = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"equip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint equip_level
    {
      get { return _equip_level; }
      set { _equip_level = value; }
    }
    private protomsg.Coord _pos = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protomsg.Coord pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleArmy")]
  public partial class BattleArmy : global::ProtoBuf.IExtensible
  {
    public BattleArmy() {}
    
    private readonly global::System.Collections.Generic.List<protomsg.BattleHero> _heroes = new global::System.Collections.Generic.List<protomsg.BattleHero>();
    [global::ProtoBuf.ProtoMember(1, Name=@"heroes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protomsg.BattleHero> heroes
    {
      get { return _heroes; }
    }
  
    private readonly global::System.Collections.Generic.List<protomsg.BattleTroop> _troops = new global::System.Collections.Generic.List<protomsg.BattleTroop>();
    [global::ProtoBuf.ProtoMember(2, Name=@"troops", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protomsg.BattleTroop> troops
    {
      get { return _troops; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleRole")]
  public partial class BattleRole : global::ProtoBuf.IExtensible
  {
    public BattleRole() {}
    
    private ulong _player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private ulong _guild_id = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"guild_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guild_id
    {
      get { return _guild_id; }
      set { _guild_id = value; }
    }
    private string _guild_name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"guild_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guild_name
    {
      get { return _guild_name; }
      set { _guild_name = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _cup = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"cup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cup
    {
      get { return _cup; }
      set { _cup = value; }
    }
    private uint _role_type = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"role_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_type
    {
      get { return _role_type; }
      set { _role_type = value; }
    }
    private uint _gs_id = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"gs_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gs_id
    {
      get { return _gs_id; }
      set { _gs_id = value; }
    }
    private uint _head = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint head
    {
      get { return _head; }
      set { _head = value; }
    }
    private uint _exp = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private protomsg.BattleArmy _army = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"army", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protomsg.BattleArmy army
    {
      get { return _army; }
      set { _army = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleInfo")]
  public partial class BattleInfo : global::ProtoBuf.IExtensible
  {
    public BattleInfo() {}
    
    private ulong _battle_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"battle_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong battle_id
    {
      get { return _battle_id; }
      set { _battle_id = value; }
    }
    private uint _battle_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"battle_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint battle_type
    {
      get { return _battle_type; }
      set { _battle_type = value; }
    }
    private uint _scene_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"scene_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint scene_id
    {
      get { return _scene_id; }
      set { _scene_id = value; }
    }
    private uint _random_seed = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"random_seed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint random_seed
    {
      get { return _random_seed; }
      set { _random_seed = value; }
    }
    private readonly global::System.Collections.Generic.List<protomsg.BattleRole> _attackers = new global::System.Collections.Generic.List<protomsg.BattleRole>();
    [global::ProtoBuf.ProtoMember(5, Name=@"attackers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protomsg.BattleRole> attackers
    {
      get { return _attackers; }
    }
  
    private readonly global::System.Collections.Generic.List<protomsg.BattleRole> _defenders = new global::System.Collections.Generic.List<protomsg.BattleRole>();
    [global::ProtoBuf.ProtoMember(6, Name=@"defenders", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protomsg.BattleRole> defenders
    {
      get { return _defenders; }
    }
  
    private uint _sub_type = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sub_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sub_type
    {
      get { return _sub_type; }
      set { _sub_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleResultInfo")]
  public partial class BattleResultInfo : global::ProtoBuf.IExtensible
  {
    public BattleResultInfo() {}
    
    private ulong _battle_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"battle_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong battle_id
    {
      get { return _battle_id; }
      set { _battle_id = value; }
    }
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<protomsg.BattleRole> _attacker = new global::System.Collections.Generic.List<protomsg.BattleRole>();
    [global::ProtoBuf.ProtoMember(3, Name=@"attacker", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protomsg.BattleRole> attacker
    {
      get { return _attacker; }
    }
  
    private readonly global::System.Collections.Generic.List<protomsg.BattleRole> _defender = new global::System.Collections.Generic.List<protomsg.BattleRole>();
    [global::ProtoBuf.ProtoMember(4, Name=@"defender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protomsg.BattleRole> defender
    {
      get { return _defender; }
    }
  
    private string _battle_guid = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"battle_guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string battle_guid
    {
      get { return _battle_guid; }
      set { _battle_guid = value; }
    }
    private uint _battle_type = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"battle_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint battle_type
    {
      get { return _battle_type; }
      set { _battle_type = value; }
    }
    private uint _sub_type = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sub_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sub_type
    {
      get { return _sub_type; }
      set { _sub_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleCommand")]
  public partial class BattleCommand : global::ProtoBuf.IExtensible
  {
    public BattleCommand() {}
    
    private uint _command_type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"command_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint command_type
    {
      get { return _command_type; }
      set { _command_type = value; }
    }
    private ulong _player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private uint _require_frame = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"require_frame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint require_frame
    {
      get { return _require_frame; }
      set { _require_frame = value; }
    }
    private uint _execute_frame = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"execute_frame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint execute_frame
    {
      get { return _execute_frame; }
      set { _execute_frame = value; }
    }
    private uint _command_index = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"command_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint command_index
    {
      get { return _command_index; }
      set { _command_index = value; }
    }
    private uint _unit_id = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"unit_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint unit_id
    {
      get { return _unit_id; }
      set { _unit_id = value; }
    }
    private protomsg.Coord _coord = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"coord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protomsg.Coord coord
    {
      get { return _coord; }
      set { _coord = value; }
    }
    private uint _skill_id = default(uint);
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private protomsg.Coord _direction = null;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protomsg.Coord direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private protomsg.Coord _target_pos = null;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"target_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protomsg.Coord target_pos
    {
      get { return _target_pos; }
      set { _target_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroInfo")]
  public partial class HeroInfo : global::ProtoBuf.IExtensible
  {
    public HeroInfo() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _hero_chip = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hero_chip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hero_chip
    {
      get { return _hero_chip; }
      set { _hero_chip = value; }
    }
    private uint _equip_level = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"equip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint equip_level
    {
      get { return _equip_level; }
      set { _equip_level = value; }
    }
    private uint _equip_chip = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"equip_chip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint equip_chip
    {
      get { return _equip_chip; }
      set { _equip_chip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArmyLineup")]
  public partial class ArmyLineup : global::ProtoBuf.IExtensible
  {
    public ArmyLineup() {}
    
    private readonly global::System.Collections.Generic.List<uint> _heroes = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"heroes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> heroes
    {
      get { return _heroes; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _troops = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"troops", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> troops
    {
      get { return _troops; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaChest")]
  public partial class ArenaChest : global::ProtoBuf.IExtensible
  {
    public ArenaChest() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _status = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private ulong _time = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleRecordPlayer")]
  public partial class BattleRecordPlayer : global::ProtoBuf.IExtensible
  {
    public BattleRecordPlayer() {}
    
    private ulong _id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private ulong _guild_id = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"guild_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guild_id
    {
      get { return _guild_id; }
      set { _guild_id = value; }
    }
    private string _guild_name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"guild_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guild_name
    {
      get { return _guild_name; }
      set { _guild_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleRecord")]
  public partial class BattleRecord : global::ProtoBuf.IExtensible
  {
    public BattleRecord() {}
    
    private string _guid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private uint _battle_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"battle_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint battle_type
    {
      get { return _battle_type; }
      set { _battle_type = value; }
    }
    private ulong _time = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<protomsg.BattleRecordPlayer> _attackers = new global::System.Collections.Generic.List<protomsg.BattleRecordPlayer>();
    [global::ProtoBuf.ProtoMember(5, Name=@"attackers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protomsg.BattleRecordPlayer> attackers
    {
      get { return _attackers; }
    }
  
    private readonly global::System.Collections.Generic.List<protomsg.BattleRecordPlayer> _defenders = new global::System.Collections.Generic.List<protomsg.BattleRecordPlayer>();
    [global::ProtoBuf.ProtoMember(6, Name=@"defenders", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protomsg.BattleRecordPlayer> defenders
    {
      get { return _defenders; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CaravanInfo")]
  public partial class CaravanInfo : global::ProtoBuf.IExtensible
  {
    public CaravanInfo() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _status = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private ulong _time = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchCaravanInfo")]
  public partial class MatchCaravanInfo : global::ProtoBuf.IExtensible
  {
    public MatchCaravanInfo() {}
    
    private ulong _player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private uint _caravan_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"caravan_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint caravan_id
    {
      get { return _caravan_id; }
      set { _caravan_id = value; }
    }
    private protomsg.BattleRole _role = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protomsg.BattleRole role
    {
      get { return _role; }
      set { _role = value; }
    }
    private readonly global::System.Collections.Generic.List<protomsg.Resource> _resources = new global::System.Collections.Generic.List<protomsg.Resource>();
    [global::ProtoBuf.ProtoMember(4, Name=@"resources", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protomsg.Resource> resources
    {
      get { return _resources; }
    }
  
    private ulong _expired_time = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"expired_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong expired_time
    {
      get { return _expired_time; }
      set { _expired_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RobResource")]
  public partial class RobResource : global::ProtoBuf.IExtensible
  {
    public RobResource() {}
    
    private uint _resource_type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"resource_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint resource_type
    {
      get { return _resource_type; }
      set { _resource_type = value; }
    }
    private uint _base_rob_value = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"base_rob_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint base_rob_value
    {
      get { return _base_rob_value; }
      set { _base_rob_value = value; }
    }
    private uint _reward_value = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reward_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reward_value
    {
      get { return _reward_value; }
      set { _reward_value = value; }
    }
    private uint _reduce_value = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"reduce_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reduce_value
    {
      get { return _reduce_value; }
      set { _reduce_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PVEEnemy")]
  public partial class PVEEnemy : global::ProtoBuf.IExtensible
  {
    public PVEEnemy() {}
    
    private ulong _id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private protomsg.BattleRole _role = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protomsg.BattleRole role
    {
      get { return _role; }
      set { _role = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private protomsg.Coord _pos = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protomsg.Coord pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RobEnemiesData")]
  public partial class RobEnemiesData : global::ProtoBuf.IExtensible
  {
    public RobEnemiesData() {}
    
    private readonly global::System.Collections.Generic.List<protomsg.PVEEnemy> _enemies = new global::System.Collections.Generic.List<protomsg.PVEEnemy>();
    [global::ProtoBuf.ProtoMember(1, Name=@"enemies", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protomsg.PVEEnemy> enemies
    {
      get { return _enemies; }
    }
  
    private ulong _reflesh_time = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reflesh_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong reflesh_time
    {
      get { return _reflesh_time; }
      set { _reflesh_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MistEnemiesData")]
  public partial class MistEnemiesData : global::ProtoBuf.IExtensible
  {
    public MistEnemiesData() {}
    
    private readonly global::System.Collections.Generic.List<protomsg.PVEEnemy> _enemies = new global::System.Collections.Generic.List<protomsg.PVEEnemy>();
    [global::ProtoBuf.ProtoMember(1, Name=@"enemies", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protomsg.PVEEnemy> enemies
    {
      get { return _enemies; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapEnemiesData")]
  public partial class MapEnemiesData : global::ProtoBuf.IExtensible
  {
    public MapEnemiesData() {}
    
    private ulong _reflesh_time = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reflesh_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong reflesh_time
    {
      get { return _reflesh_time; }
      set { _reflesh_time = value; }
    }
    private readonly global::System.Collections.Generic.List<protomsg.PVEEnemy> _enemies = new global::System.Collections.Generic.List<protomsg.PVEEnemy>();
    [global::ProtoBuf.ProtoMember(2, Name=@"enemies", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protomsg.PVEEnemy> enemies
    {
      get { return _enemies; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ViewPVEEnemy")]
  public partial class ViewPVEEnemy : global::ProtoBuf.IExtensible
  {
    public ViewPVEEnemy() {}
    
    private ulong _id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private protomsg.BattleRole _role = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protomsg.BattleRole role
    {
      get { return _role; }
      set { _role = value; }
    }
    private readonly global::System.Collections.Generic.List<protomsg.RobResource> _rob_resource = new global::System.Collections.Generic.List<protomsg.RobResource>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rob_resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protomsg.RobResource> rob_resource
    {
      get { return _rob_resource; }
    }
  
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailResource")]
  public partial class MailResource : global::ProtoBuf.IExtensible
  {
    public MailResource() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private ulong _val = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong val
    {
      get { return _val; }
      set { _val = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceSet")]
  public partial class ResourceSet : global::ProtoBuf.IExtensible
  {
    public ResourceSet() {}
    
    private readonly global::System.Collections.Generic.List<protomsg.MailResource> _res = new global::System.Collections.Generic.List<protomsg.MailResource>();
    [global::ProtoBuf.ProtoMember(1, Name=@"res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protomsg.MailResource> res
    {
      get { return _res; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SysAnnFilter")]
  public partial class SysAnnFilter : global::ProtoBuf.IExtensible
  {
    public SysAnnFilter() {}
    
    private uint _min_lv = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"min_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint min_lv
    {
      get { return _min_lv; }
      set { _min_lv = value; }
    }
    private uint _max_lv = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"max_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_lv
    {
      get { return _max_lv; }
      set { _max_lv = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"system_announcement")]
  public partial class system_announcement : global::ProtoBuf.IExtensible
  {
    public system_announcement() {}
    
    private ulong _id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _announce_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"announce_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong announce_id
    {
      get { return _announce_id; }
      set { _announce_id = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _subject = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"subject", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string subject
    {
      get { return _subject; }
      set { _subject = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private protomsg.ResourceSet _res = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"res", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protomsg.ResourceSet res
    {
      get { return _res; }
      set { _res = value; }
    }
    private uint _language = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"language", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint language
    {
      get { return _language; }
      set { _language = value; }
    }
    private protomsg.SysAnnFilter _filter = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"filter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protomsg.SysAnnFilter filter
    {
      get { return _filter; }
      set { _filter = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"UsPlayerStatus")]
    public enum UsPlayerStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPsOffline", Value=0)]
      kPsOffline = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPsOnline", Value=1)]
      kPsOnline = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPsOfflineCache", Value=2)]
      kPsOfflineCache = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ResourceType")]
    public enum ResourceType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kResourceNone", Value=0)]
      kResourceNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kResourceGold", Value=1)]
      kResourceGold = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kResourceFood", Value=2)]
      kResourceFood = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kResourceWood", Value=3)]
      kResourceWood = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kResourceEmoney", Value=4)]
      kResourceEmoney = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PlayerAttributeType")]
    public enum PlayerAttributeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrNone", Value=0)]
      kPlayerAttrNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrGold", Value=1)]
      kPlayerAttrGold = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrFood", Value=2)]
      kPlayerAttrFood = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrWood", Value=3)]
      kPlayerAttrWood = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrEmoney", Value=4)]
      kPlayerAttrEmoney = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrPower", Value=5)]
      kPlayerAttrPower = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrPopulation", Value=6)]
      kPlayerAttrPopulation = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrExp", Value=7)]
      kPlayerAttrExp = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrCup", Value=8)]
      kPlayerAttrCup = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrPoint", Value=9)]
      kPlayerAttrPoint = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrContribute", Value=10)]
      kPlayerAttrContribute = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrLevel", Value=11)]
      kPlayerAttrLevel = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrNormalHero", Value=1000)]
      kPlayerAttrNormalHero = 1000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrRareHero", Value=1001)]
      kPlayerAttrRareHero = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrEpicHero", Value=1002)]
      kPlayerAttrEpicHero = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrLegendHero", Value=1003)]
      kPlayerAttrLegendHero = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrEquip", Value=1004)]
      kPlayerAttrEquip = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerAttrSoldierEquip", Value=1005)]
      kPlayerAttrSoldierEquip = 1005
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PlayerExtendAttribute")]
    public enum PlayerExtendAttribute
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrNone", Value=0)]
      kExtendAttrNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrGoldProduce", Value=101)]
      kExtendAttrGoldProduce = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrFoodProduce", Value=102)]
      kExtendAttrFoodProduce = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrWoodProduce", Value=103)]
      kExtendAttrWoodProduce = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrGoldCache", Value=111)]
      kExtendAttrGoldCache = 111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrFoodCache", Value=112)]
      kExtendAttrFoodCache = 112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrWoodCache", Value=113)]
      kExtendAttrWoodCache = 113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrGoldStore", Value=121)]
      kExtendAttrGoldStore = 121,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrFoodStore", Value=122)]
      kExtendAttrFoodStore = 122,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrWoodStore", Value=123)]
      kExtendAttrWoodStore = 123,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrPowerStore", Value=124)]
      kExtendAttrPowerStore = 124,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrGoldSafe", Value=131)]
      kExtendAttrGoldSafe = 131,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrFoodSafe", Value=132)]
      kExtendAttrFoodSafe = 132,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrWoodSafe", Value=133)]
      kExtendAttrWoodSafe = 133,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrProtectRate", Value=134)]
      kExtendAttrProtectRate = 134,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrGoldSpeedupRate", Value=141)]
      kExtendAttrGoldSpeedupRate = 141,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrFoodSpeedupRate", Value=142)]
      kExtendAttrFoodSpeedupRate = 142,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrWoodSpeedupRate", Value=143)]
      kExtendAttrWoodSpeedupRate = 143,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrGoldRobRate", Value=151)]
      kExtendAttrGoldRobRate = 151,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrFoodRobRate", Value=152)]
      kExtendAttrFoodRobRate = 152,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrWoodRobRate", Value=153)]
      kExtendAttrWoodRobRate = 153,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrReduceRobRate", Value=154)]
      kExtendAttrReduceRobRate = 154,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrGoldCacheAddRate", Value=161)]
      kExtendAttrGoldCacheAddRate = 161,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrFoodCacheAddRate", Value=162)]
      kExtendAttrFoodCacheAddRate = 162,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrWoodCacheAddRate", Value=163)]
      kExtendAttrWoodCacheAddRate = 163,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrGoldCaravan", Value=171)]
      kExtendAttrGoldCaravan = 171,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrFoodCaravan", Value=172)]
      kExtendAttrFoodCaravan = 172,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrWoodCaravan", Value=173)]
      kExtendAttrWoodCaravan = 173,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrArmySpeedupRate", Value=201)]
      kExtendAttrArmySpeedupRate = 201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kExtendAttrConstructSpeedupRate", Value=202)]
      kExtendAttrConstructSpeedupRate = 202
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MailType")]
    public enum MailType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMailTypeSystem", Value=0)]
      kMailTypeSystem = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMailTypeGuild", Value=1)]
      kMailTypeGuild = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MailReadFlag")]
    public enum MailReadFlag
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMailFlagUnread", Value=0)]
      kMailFlagUnread = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMailFlagRead", Value=1)]
      kMailFlagRead = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMailFlagExtract", Value=2)]
      kMailFlagExtract = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgLanguageType")]
    public enum MsgLanguageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageEnglish", Value=0)]
      kLanguageEnglish = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageChineseCN", Value=1)]
      kLanguageChineseCN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageChineseTW", Value=2)]
      kLanguageChineseTW = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageFrench", Value=3)]
      kLanguageFrench = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageItalian", Value=4)]
      kLanguageItalian = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageGerman", Value=5)]
      kLanguageGerman = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageSpanish", Value=6)]
      kLanguageSpanish = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageDutch", Value=7)]
      kLanguageDutch = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageRussian", Value=8)]
      kLanguageRussian = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageKorean", Value=9)]
      kLanguageKorean = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageJapanese", Value=10)]
      kLanguageJapanese = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageHungrian", Value=11)]
      kLanguageHungrian = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguagePortuguese", Value=12)]
      kLanguagePortuguese = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageArabic", Value=13)]
      kLanguageArabic = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageNorwegian", Value=14)]
      kLanguageNorwegian = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguagePolish", Value=15)]
      kLanguagePolish = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageTurkish", Value=16)]
      kLanguageTurkish = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageUkrainian", Value=17)]
      kLanguageUkrainian = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageRomanian", Value=18)]
      kLanguageRomanian = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageBulgarian", Value=19)]
      kLanguageBulgarian = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageCzech", Value=20)]
      kLanguageCzech = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageDanish", Value=21)]
      kLanguageDanish = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageGreek", Value=22)]
      kLanguageGreek = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageFinnish", Value=23)]
      kLanguageFinnish = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageSlovak", Value=24)]
      kLanguageSlovak = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageSwedish", Value=25)]
      kLanguageSwedish = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageVietnamese", Value=26)]
      kLanguageVietnamese = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageThai", Value=27)]
      kLanguageThai = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageCatalan", Value=28)]
      kLanguageCatalan = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageHebrew", Value=29)]
      kLanguageHebrew = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageIndonesian", Value=30)]
      kLanguageIndonesian = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageMalay", Value=31)]
      kLanguageMalay = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kLanguageFarsi", Value=32)]
      kLanguageFarsi = 32
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgGuildPosition")]
    public enum MsgGuildPosition
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGuildPositionNone", Value=0)]
      kMsgGuildPositionNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGuildPositionMember", Value=1)]
      kMsgGuildPositionMember = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGuildPositionLeader", Value=2)]
      kMsgGuildPositionLeader = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGuildPositionViceMaster", Value=3)]
      kMsgGuildPositionViceMaster = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGuildPositionMaster", Value=4)]
      kMsgGuildPositionMaster = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgGuildJoinType")]
    public enum MsgGuildJoinType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGuildJoinTypeAllow", Value=0)]
      kMsgGuildJoinTypeAllow = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGuildJoinTypeApply", Value=1)]
      kMsgGuildJoinTypeApply = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGuildJoinTypeForbidden", Value=2)]
      kMsgGuildJoinTypeForbidden = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGuildJoinTypeCount", Value=3)]
      kMsgGuildJoinTypeCount = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgConstructionStatus")]
    public enum MsgConstructionStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kConstructionStatusNone", Value=0)]
      kConstructionStatusNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kConstructionStatusBuilding", Value=1)]
      kConstructionStatusBuilding = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kConstructionStatusWaitActive", Value=2)]
      kConstructionStatusWaitActive = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kConstructionStatusNormal", Value=3)]
      kConstructionStatusNormal = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kConstructionStatusCount", Value=4)]
      kConstructionStatusCount = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BattleType")]
    public enum BattleType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBattleTypeNone", Value=0)]
      kBattleTypeNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBattleTypePVE", Value=1)]
      kBattleTypePVE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBattleTypePVP", Value=2)]
      kBattleTypePVP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBattleTypeEnd", Value=3)]
      kBattleTypeEnd = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PVPSubType")]
    public enum PVPSubType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPVPNone", Value=0)]
      kPVPNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPVPArena", Value=1)]
      kPVPArena = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPVPCaravan", Value=2)]
      kPVPCaravan = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BattleRoleType")]
    public enum BattleRoleType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBattleRoleSystem", Value=0)]
      kBattleRoleSystem = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBattleRolePlayer", Value=1)]
      kBattleRolePlayer = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBattleRoleRobot", Value=2)]
      kBattleRoleRobot = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BattleResultType")]
    public enum BattleResultType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBattleResultDraw", Value=0)]
      kBattleResultDraw = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBattleResultAttackerWin", Value=1)]
      kBattleResultAttackerWin = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBattleResultDefenderWin", Value=2)]
      kBattleResultDefenderWin = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBattleResultCancel", Value=3)]
      kBattleResultCancel = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PlayerBattleResultType")]
    public enum PlayerBattleResultType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerBattleResultDraw", Value=0)]
      kPlayerBattleResultDraw = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerBattleResultLose", Value=1)]
      kPlayerBattleResultLose = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPlayerBattleResultWin", Value=2)]
      kPlayerBattleResultWin = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BattleCommandType")]
    public enum BattleCommandType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBattleCommandNone", Value=0)]
      kBattleCommandNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBattleCommandDeploy", Value=1)]
      kBattleCommandDeploy = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBattleCommandSkill", Value=2)]
      kBattleCommandSkill = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBattleCommandAuto", Value=3)]
      kBattleCommandAuto = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBattleCommandManual", Value=4)]
      kBattleCommandManual = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kBattleCommandGiveup", Value=5)]
      kBattleCommandGiveup = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"HeroQualityType")]
    public enum HeroQualityType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kHeroQualityNone", Value=0)]
      kHeroQualityNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kHeroQualityNormal", Value=1)]
      kHeroQualityNormal = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kHeroQualityRare", Value=2)]
      kHeroQualityRare = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kHeroQualityEpic", Value=3)]
      kHeroQualityEpic = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kHeroQualityLegend", Value=4)]
      kHeroQualityLegend = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"HeroRaceType")]
    public enum HeroRaceType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kHeroRaceNone", Value=0)]
      kHeroRaceNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kHeroRaceHuman", Value=1)]
      kHeroRaceHuman = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kHeroRaceElf", Value=2)]
      kHeroRaceElf = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kHeroRaceOrc", Value=3)]
      kHeroRaceOrc = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kHeroRaceUndead", Value=4)]
      kHeroRaceUndead = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kHeroRaceDevil", Value=5)]
      kHeroRaceDevil = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ArenaChestStatus")]
    public enum ArenaChestStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kChestStatusNone", Value=0)]
      kChestStatusNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kChestStatusLock", Value=1)]
      kChestStatusLock = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kChestStatusUnlocking", Value=2)]
      kChestStatusUnlocking = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kChestStatusReady", Value=3)]
      kChestStatusReady = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ArenaChestType")]
    public enum ArenaChestType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kArenaChestTypeNone", Value=0)]
      kArenaChestTypeNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kArenaChestTypeBronze", Value=1)]
      kArenaChestTypeBronze = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kArenaChestTypeSilver", Value=2)]
      kArenaChestTypeSilver = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kArenaChestTypeGold", Value=3)]
      kArenaChestTypeGold = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kArenaChestTypeLarge", Value=4)]
      kArenaChestTypeLarge = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kArenaChestTypeWonder", Value=5)]
      kArenaChestTypeWonder = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kArenaChestTypeSuperWonder", Value=6)]
      kArenaChestTypeSuperWonder = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kArenaChestTypeEpic", Value=7)]
      kArenaChestTypeEpic = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kArenaChestTypeLegend", Value=8)]
      kArenaChestTypeLegend = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kArenaChestTypeDiamond", Value=9)]
      kArenaChestTypeDiamond = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kArenaChestTypeEquip", Value=10)]
      kArenaChestTypeEquip = 10
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CaravanStatus")]
    public enum CaravanStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kCaravanReady", Value=0)]
      kCaravanReady = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kCaravanCooldown", Value=1)]
      kCaravanCooldown = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PVEType")]
    public enum PVEType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPVETypeNone", Value=0)]
      kPVETypeNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPVETypeRob", Value=1)]
      kPVETypeRob = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPVETypeMist", Value=2)]
      kPVETypeMist = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPVETypeMap", Value=3)]
      kPVETypeMap = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kPVETypeSearch", Value=4)]
      kPVETypeSearch = 4
    }
  
}