//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: msgtype.proto
namespace msgtype
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgTypeData")]
  public partial class MsgTypeData : global::ProtoBuf.IExtensible
  {
    public MsgTypeData() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgType")]
    public enum MsgType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgServerBegin", Value=0)]
      kMsgServerBegin = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCoreMsgTypeStart", Value=1)]
      kMsgCoreMsgTypeStart = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCoreMsgTypeEnd", Value=100)]
      kMsgCoreMsgTypeEnd = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgServerKeepLive", Value=1000)]
      kMsgServerKeepLive = 1000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgServerRegist", Value=1001)]
      kMsgServerRegist = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgServiceReady", Value=1002)]
      kMsgServiceReady = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgServiceBreak", Value=1003)]
      kMsgServiceBreak = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgServerShutdown", Value=1004)]
      kMsgServerShutdown = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgServerConfigNotice", Value=1005)]
      kMsgServerConfigNotice = 1005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgServerTransfer", Value=1030)]
      kMsgServerTransfer = 1030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgBigPackage", Value=1031)]
      kMsgBigPackage = 1031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgServerEventListen", Value=1130)]
      kMsgServerEventListen = 1130,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgServerEventNotice", Value=1131)]
      kMsgServerEventNotice = 1131,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgServerLinkInfoRequest", Value=1132)]
      kMsgServerLinkInfoRequest = 1132,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgServerLinkInfoReply", Value=1133)]
      kMsgServerLinkInfoReply = 1133,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgSeverReloadNotice", Value=1134)]
      kMsgSeverReloadNotice = 1134,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2USLoadInfoNotice", Value=1160)]
      kMsgGS2USLoadInfoNotice = 1160,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgClientBegin", Value=2000)]
      kMsgClientBegin = 2000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerLoginBegin", Value=2001)]
      kMsgPlayerLoginBegin = 2001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgLS2GSRegisterPlayerLoginRequest", Value=2006)]
      kMsgLS2GSRegisterPlayerLoginRequest = 2006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2LSRegisterPlayerLoginReply", Value=2007)]
      kMsgGS2LSRegisterPlayerLoginReply = 2007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2USPlayerOnlineNotice", Value=2008)]
      kMsgGS2USPlayerOnlineNotice = 2008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2USPlayerOfflineNotice", Value=2009)]
      kMsgGS2USPlayerOfflineNotice = 2009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgUS2GSKickPlayerNotice", Value=2012)]
      kMsgUS2GSKickPlayerNotice = 2012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgLS2GSKickPlayerNotice", Value=2013)]
      kMsgLS2GSKickPlayerNotice = 2013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2USPlayerOfflineCacheNotice", Value=2014)]
      kMsgGS2USPlayerOfflineCacheNotice = 2014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2PMSPlayerOnlineNotice", Value=2017)]
      kMsgGS2PMSPlayerOnlineNotice = 2017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2PMSPlayerOfflineNotice", Value=2018)]
      kMsgGS2PMSPlayerOfflineNotice = 2018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPMS2GSGetPlayerPVEDefendRequest", Value=2019)]
      kMsgPMS2GSGetPlayerPVEDefendRequest = 2019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPMS2GSGetPlayerPVEDefendReply", Value=2020)]
      kMsgPMS2GSGetPlayerPVEDefendReply = 2020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2LSLoginRequest", Value=2030)]
      kMsgCL2LSLoginRequest = 2030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgLS2CLLoginReply", Value=2031)]
      kMsgLS2CLLoginReply = 2031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgLS2CLLoginFailed", Value=2032)]
      kMsgLS2CLLoginFailed = 2032,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSLoginRequest", Value=2060)]
      kMsgCL2GSLoginRequest = 2060,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLLoginReply", Value=2061)]
      kMsgGS2CLLoginReply = 2061,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSEnterGameRequest", Value=2063)]
      kMsgCL2GSEnterGameRequest = 2063,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLEnterGameReply", Value=2064)]
      kMsgGS2CLEnterGameReply = 2064,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLNewPlayerNotice", Value=2065)]
      kMsgGS2CLNewPlayerNotice = 2065,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerLoginEnd", Value=2200)]
      kMsgPlayerLoginEnd = 2200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPMBegin", Value=2201)]
      kMsgPMBegin = 2201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSPMCommandRequest", Value=2202)]
      kMsgCL2GSPMCommandRequest = 2202,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPMCommandReply", Value=2203)]
      kMsgGS2CLPMCommandReply = 2203,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSTestRequest", Value=2210)]
      kMsgCL2GSTestRequest = 2210,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLTestReply", Value=2211)]
      kMsgGS2CLTestReply = 2211,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPMEnd", Value=2300)]
      kMsgPMEnd = 2300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerBaseBegin", Value=2301)]
      kMsgPlayerBaseBegin = 2301,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPlayerBaseNotice", Value=2302)]
      kMsgGS2CLPlayerBaseNotice = 2302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSRenameRequest", Value=2303)]
      kMsgCL2GSRenameRequest = 2303,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLRenameReply", Value=2304)]
      kMsgGS2CLRenameReply = 2304,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSKeepLiveRequest", Value=2305)]
      kMsgCL2GSKeepLiveRequest = 2305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLKeepLiveReply", Value=2306)]
      kMsgGS2CLKeepLiveReply = 2306,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLServerTimeNotice", Value=2307)]
      kMsgGS2CLServerTimeNotice = 2307,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPlayerAttribute", Value=2308)]
      kMsgGS2CLPlayerAttribute = 2308,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSGemToResource", Value=2309)]
      kMsgCL2GSGemToResource = 2309,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerBaseEnd", Value=2400)]
      kMsgPlayerBaseEnd = 2400,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerGuildBegin", Value=2401)]
      kMsgPlayerGuildBegin = 2401,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2GuildApplyingNotice", Value=2404)]
      kMsgGS2GuildApplyingNotice = 2404,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2GuildJoinNotice", Value=2405)]
      kMsgGS2GuildJoinNotice = 2405,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2GuildQuitNotice", Value=2406)]
      kMsgGS2GuildQuitNotice = 2406,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2GuildPositionNotice", Value=2407)]
      kMsgGS2GuildPositionNotice = 2407,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2GuildRenameNotice", Value=2408)]
      kMsgGS2GuildRenameNotice = 2408,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2GuildLevelNotice", Value=2409)]
      kMsgGS2GuildLevelNotice = 2409,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2GuildCupNotice", Value=2410)]
      kMsgGS2GuildCupNotice = 2410,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2GuildChargeNotice", Value=2411)]
      kMsgGS2GuildChargeNotice = 2411,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2GuildHeadNotice", Value=2412)]
      kMsgGS2GuildHeadNotice = 2412,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2GuildDestroyNotice", Value=2413)]
      kMsgGS2GuildDestroyNotice = 2413,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSGuildBaseInfoRequest", Value=2421)]
      kMsgCL2GSGuildBaseInfoRequest = 2421,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLGuildBaseInfoReply", Value=2422)]
      kMsgGS2CLGuildBaseInfoReply = 2422,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSGuildCreateRequest", Value=2423)]
      kMsgCL2GSGuildCreateRequest = 2423,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLGuildCreateReply", Value=2424)]
      kMsgGS2CLGuildCreateReply = 2424,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLGuildJoinNotice", Value=2425)]
      kMsgGS2CLGuildJoinNotice = 2425,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLGuildQuitNotice", Value=2426)]
      kMsgGS2CLGuildQuitNotice = 2426,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSGuildJoinRequest", Value=2427)]
      kMsgCL2GSGuildJoinRequest = 2427,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLGuildJoinReply", Value=2428)]
      kMsgGS2CLGuildJoinReply = 2428,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSGuildQuitRequest", Value=2429)]
      kMsgCL2GSGuildQuitRequest = 2429,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLGuildQuitReply", Value=2430)]
      kMsgGS2CLGuildQuitReply = 2430,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSGuildListApplicantRequest", Value=2431)]
      kMsgCL2GSGuildListApplicantRequest = 2431,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLGuildListApplicantReply", Value=2432)]
      kMsgGS2CLGuildListApplicantReply = 2432,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSGuildAnswerApplyRequest", Value=2433)]
      kMsgCL2GSGuildAnswerApplyRequest = 2433,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLGuildAnswerApplyReply", Value=2434)]
      kMsgGS2CLGuildAnswerApplyReply = 2434,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSGuildPromoteRequest", Value=2435)]
      kMsgCL2GSGuildPromoteRequest = 2435,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLGuildPromoteReply", Value=2436)]
      kMsgGS2CLGuildPromoteReply = 2436,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSGuildDemoteRequest", Value=2437)]
      kMsgCL2GSGuildDemoteRequest = 2437,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLGuildDemoteReply", Value=2438)]
      kMsgGS2CLGuildDemoteReply = 2438,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSGuildQueryRequest", Value=2439)]
      kMsgCL2GSGuildQueryRequest = 2439,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLGuildQuserReply", Value=2440)]
      kMsgGS2CLGuildQuserReply = 2440,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSGuildKickMemberRequest", Value=2441)]
      kMsgCL2GSGuildKickMemberRequest = 2441,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLGuildKickMemberReply", Value=2442)]
      kMsgGS2CLGuildKickMemberReply = 2442,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSGuildSetBulletinRequest", Value=2443)]
      kMsgCL2GSGuildSetBulletinRequest = 2443,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLGuildSetBulletinReply", Value=2444)]
      kMsgGS2CLGuildSetBulletinReply = 2444,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSGuildSetJoinConditionRequest", Value=2445)]
      kMsgCL2GSGuildSetJoinConditionRequest = 2445,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLGuildSetJoinConditionReply", Value=2446)]
      kMsgGS2CLGuildSetJoinConditionReply = 2446,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLGuildPositionNotice", Value=2447)]
      kMsgGS2CLGuildPositionNotice = 2447,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSGuildSearchRequest", Value=2448)]
      kMsgCL2GSGuildSearchRequest = 2448,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLGuildSearchReply", Value=2449)]
      kMsgGS2CLGuildSearchReply = 2449,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSGuildSendMailRequest", Value=2450)]
      kMsgCL2GSGuildSendMailRequest = 2450,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLGuildSendMailReply", Value=2451)]
      kMsgGS2CLGuildSendMailReply = 2451,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerGuildEnd", Value=2500)]
      kMsgPlayerGuildEnd = 2500,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerMailBegin", Value=2501)]
      kMsgPlayerMailBegin = 2501,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgMail2GSMailNewNotice", Value=2502)]
      kMsgMail2GSMailNewNotice = 2502,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgMail2GSMailNewSysAnnounce", Value=2503)]
      kMsgMail2GSMailNewSysAnnounce = 2503,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLMailIDListNotice", Value=2521)]
      kMsgGS2CLMailIDListNotice = 2521,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSMailListRequest", Value=2522)]
      kMsgCL2GSMailListRequest = 2522,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLMailListReply", Value=2533)]
      kMsgGS2CLMailListReply = 2533,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLMailNewNotice", Value=2534)]
      kMsgGS2CLMailNewNotice = 2534,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSMailUpdateReadRequest", Value=2535)]
      kMsgCL2GSMailUpdateReadRequest = 2535,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLMailUpdateReadReply", Value=2536)]
      kMsgGS2CLMailUpdateReadReply = 2536,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSMailUpdateBatchRequest", Value=2537)]
      kMsgCL2GSMailUpdateBatchRequest = 2537,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLMailUpdateBatchReply", Value=2538)]
      kMsgGS2CLMailUpdateBatchReply = 2538,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSMailDeleteRequest", Value=2539)]
      kMsgCL2GSMailDeleteRequest = 2539,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLMailDeleteReply", Value=2540)]
      kMsgGS2CLMailDeleteReply = 2540,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSMailDeleteBatchRequest", Value=2541)]
      kMsgCL2GSMailDeleteBatchRequest = 2541,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLMailDeleteBatchReply", Value=2542)]
      kMsgGS2CLMailDeleteBatchReply = 2542,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLMailDeleteNotice", Value=2543)]
      kMsgGS2CLMailDeleteNotice = 2543,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerMailEnd", Value=2600)]
      kMsgPlayerMailEnd = 2600,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerPackageBegin", Value=2601)]
      kMsgPlayerPackageBegin = 2601,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLBigPackage", Value=2621)]
      kMsgGS2CLBigPackage = 2621,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerPackageEnd", Value=2700)]
      kMsgPlayerPackageEnd = 2700,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerBuildingBegin", Value=2701)]
      kMsgPlayerBuildingBegin = 2701,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSBuildingInfoRequest", Value=2702)]
      kMsgCL2GSBuildingInfoRequest = 2702,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLBuildingInfoReply", Value=2703)]
      kMsgGS2CLBuildingInfoReply = 2703,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSBuildingCreateRequest", Value=2704)]
      kMsgCL2GSBuildingCreateRequest = 2704,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLBuildingCreateReply", Value=2705)]
      kMsgGS2CLBuildingCreateReply = 2705,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLBuildingQueueNotice", Value=2706)]
      kMsgGS2CLBuildingQueueNotice = 2706,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLBuildingUpdateNotice", Value=2707)]
      kMsgGS2CLBuildingUpdateNotice = 2707,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSBuildingUpgradeRequest", Value=2708)]
      kMsgCL2GSBuildingUpgradeRequest = 2708,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLBuildingUpgradeReply", Value=2709)]
      kMsgGS2CLBuildingUpgradeReply = 2709,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSBuildingCancelRequest", Value=2710)]
      kMsgCL2GSBuildingCancelRequest = 2710,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLBuildingCancelReply", Value=2711)]
      kMsgGS2CLBuildingCancelReply = 2711,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSBuildingActiveRequest", Value=2712)]
      kMsgCL2GSBuildingActiveRequest = 2712,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLBuildingActiveReply", Value=2713)]
      kMsgGS2CLBuildingActiveReply = 2713,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSBuildingMoveRequest", Value=2714)]
      kMsgCL2GSBuildingMoveRequest = 2714,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLBuildingMoveReply", Value=2715)]
      kMsgGS2CLBuildingMoveReply = 2715,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSBuildingSwapRequest", Value=2716)]
      kMsgCL2GSBuildingSwapRequest = 2716,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLBuildingSwapReply", Value=2717)]
      kMsgGS2CLBuildingSwapReply = 2717,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSBuildingQueryRequest", Value=2718)]
      kMsgCL2GSBuildingQueryRequest = 2718,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLBuildingQueryReply", Value=2719)]
      kMsgGS2CLBuildingQueryReply = 2719,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSBuildingUnlockMistRequest", Value=2720)]
      kMsgCL2GSBuildingUnlockMistRequest = 2720,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLBuildingUnlockMistReply", Value=2721)]
      kMsgGS2CLBuildingUnlockMistReply = 2721,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLBuildingAddLordLandNotice", Value=2722)]
      kMsgGS2CLBuildingAddLordLandNotice = 2722,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSBuildingImmediateRequest", Value=2723)]
      kMsgCL2GSBuildingImmediateRequest = 2723,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLBuildingImmediateReply", Value=2724)]
      kMsgGS2CLBuildingImmediateReply = 2724,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSBuildingInstantUpgradeRequest", Value=2725)]
      kMsgCL2GSBuildingInstantUpgradeRequest = 2725,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSBuildingInstantUpgradeReply", Value=2726)]
      kMsgCL2GSBuildingInstantUpgradeReply = 2726,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSBuildingUnlockRequest", Value=2727)]
      kMsgCL2GSBuildingUnlockRequest = 2727,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLBuildingUnlockReply", Value=2728)]
      kMsgGS2CLBuildingUnlockReply = 2728,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSBuildingOccupyLandRequest", Value=2729)]
      kMsgCL2GSBuildingOccupyLandRequest = 2729,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLBuildingOccupyLandReply", Value=2730)]
      kMsgGS2CLBuildingOccupyLandReply = 2730,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSExtendWorkQueueRequest", Value=2731)]
      kMsgCL2GSExtendWorkQueueRequest = 2731,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLExtendWorkQueueReply", Value=2732)]
      kMsgGS2CLExtendWorkQueueReply = 2732,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerBuildingEnd", Value=2800)]
      kMsgPlayerBuildingEnd = 2800,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerArmyBegin", Value=2801)]
      kMsgPlayerArmyBegin = 2801,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLArmyUnitProduceInfo", Value=2802)]
      kMsgGS2CLArmyUnitProduceInfo = 2802,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSArmyUnitRecruitRequest", Value=2803)]
      kMsgCL2GSArmyUnitRecruitRequest = 2803,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSArmyUnitSupplementRequest", Value=2804)]
      kMsgCL2GSArmyUnitSupplementRequest = 2804,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSDismissArmyUnitRequest", Value=2805)]
      kMsgCL2GSDismissArmyUnitRequest = 2805,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSAupsCompleteImmediatelyRequest", Value=2806)]
      kMsgCL2GSAupsCompleteImmediatelyRequest = 2806,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLArmyInfo", Value=2807)]
      kMsgGS2CLArmyInfo = 2807,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSArmyUpgradeRequest", Value=2808)]
      kMsgCL2GSArmyUpgradeRequest = 2808,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLArmyUpgradeProcess", Value=2809)]
      kMsgGS2CLArmyUpgradeProcess = 2809,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSArmyUpgradeCompleteRequest", Value=2810)]
      kMsgCL2GSArmyUpgradeCompleteRequest = 2810,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerArmyEnd", Value=2850)]
      kMsgPlayerArmyEnd = 2850,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerHeroBegin", Value=2851)]
      kMsgPlayerHeroBegin = 2851,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerHeroEnd", Value=2900)]
      kMsgPlayerHeroEnd = 2900,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerDefenceBegin", Value=2901)]
      kMsgPlayerDefenceBegin = 2901,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSDefenceInfoRequest", Value=2902)]
      kMsgCL2GSDefenceInfoRequest = 2902,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLDefenceInfoReply", Value=2903)]
      kMsgGS2CLDefenceInfoReply = 2903,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSDefenceUpdateRequest", Value=2904)]
      kMsgCL2GSDefenceUpdateRequest = 2904,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLDefenceUpdateReply", Value=2905)]
      kMsgGS2CLDefenceUpdateReply = 2905,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerDefenceEnd", Value=3000)]
      kMsgPlayerDefenceEnd = 3000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerEffectBegin", Value=3001)]
      kMsgPlayerEffectBegin = 3001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSEffectInfoRequest", Value=3002)]
      kMsgCL2GSEffectInfoRequest = 3002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLEffectInfoReply", Value=3003)]
      kMsgGS2CLEffectInfoReply = 3003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLEffectUpdateNotice", Value=3004)]
      kMsgGS2CLEffectUpdateNotice = 3004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLEffectProduceUpdateNotice", Value=3005)]
      kMsgGS2CLEffectProduceUpdateNotice = 3005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSEffectProduceCollectRequest", Value=3006)]
      kMsgCL2GSEffectProduceCollectRequest = 3006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLEffectProduceCollectReply", Value=3007)]
      kMsgGS2CLEffectProduceCollectReply = 3007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerEffectEnd", Value=3100)]
      kMsgPlayerEffectEnd = 3100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerBattleBegin", Value=3101)]
      kMsgPlayerBattleBegin = 3101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVPPrepareNotice", Value=3111)]
      kMsgGS2CLPVPPrepareNotice = 3111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSPVPReadyNotice", Value=3112)]
      kMsgCL2GSPVPReadyNotice = 3112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVPCountDownNotice", Value=3113)]
      kMsgGS2CLPVPCountDownNotice = 3113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVPStartNotice", Value=3114)]
      kMsgGS2CLPVPStartNotice = 3114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVPSyncFrameNotice", Value=3115)]
      kMsgGS2CLPVPSyncFrameNotice = 3115,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVPCommandNotice", Value=3116)]
      kMsgGS2CLPVPCommandNotice = 3116,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSPVPCommandRequest", Value=3117)]
      kMsgCL2GSPVPCommandRequest = 3117,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVPCommandReply", Value=3118)]
      kMsgGS2CLPVPCommandReply = 3118,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVPEndNotice", Value=3119)]
      kMsgGS2CLPVPEndNotice = 3119,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVPContinueNotice", Value=3120)]
      kMsgGS2CLPVPContinueNotice = 3120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVEStartNotice", Value=3170)]
      kMsgGS2CLPVEStartNotice = 3170,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSPVEEndNotice", Value=3171)]
      kMsgCL2GSPVEEndNotice = 3171,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgBS2GSBattlePrepareNotice", Value=3201)]
      kMsgBS2GSBattlePrepareNotice = 3201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2BSBattleReadyNotice", Value=3202)]
      kMsgGS2BSBattleReadyNotice = 3202,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgBS2GSBattleCountDownNotice", Value=3203)]
      kMsgBS2GSBattleCountDownNotice = 3203,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgBS2GSBattleStartNotice", Value=3204)]
      kMsgBS2GSBattleStartNotice = 3204,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgBS2SBattleEndNotice", Value=3205)]
      kMsgBS2SBattleEndNotice = 3205,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2BSBattlePlayerOfflineNotice", Value=3206)]
      kMsgGS2BSBattlePlayerOfflineNotice = 3206,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2BSBattleCommandNotice", Value=3207)]
      kMsgGS2BSBattleCommandNotice = 3207,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgBS2BCSLoadInfoNotice", Value=3208)]
      kMsgBS2BCSLoadInfoNotice = 3208,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgBC2BSProtectNotice", Value=3209)]
      kMsgBC2BSProtectNotice = 3209,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgBC2BSUnprotectNotice", Value=3210)]
      kMsgBC2BSUnprotectNotice = 3210,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgBC2PVEProtectNotice", Value=3211)]
      kMsgBC2PVEProtectNotice = 3211,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2BSBattleForceEndNotice", Value=3212)]
      kMsgGS2BSBattleForceEndNotice = 3212,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerBattleEnd", Value=3300)]
      kMsgPlayerBattleEnd = 3300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerHerpBegin", Value=3301)]
      kMsgPlayerHerpBegin = 3301,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSHeroInfoRequest", Value=3302)]
      kMsgCL2GSHeroInfoRequest = 3302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLHeroInfoReply", Value=3303)]
      kMsgGS2CLHeroInfoReply = 3303,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSHeroUpgradeRequest", Value=3304)]
      kMsgCL2GSHeroUpgradeRequest = 3304,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLHeroUpgradeReply", Value=3305)]
      kMsgGS2CLHeroUpgradeReply = 3305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLHeroUpdateNotice", Value=3306)]
      kMsgGS2CLHeroUpdateNotice = 3306,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLRemoveHeroNotice", Value=3307)]
      kMsgGS2CLRemoveHeroNotice = 3307,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerHerpEnd", Value=3351)]
      kMsgPlayerHerpEnd = 3351,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerArenaBegin", Value=3401)]
      kMsgPlayerArenaBegin = 3401,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSPVPApplyRequest", Value=3402)]
      kMsgCL2GSPVPApplyRequest = 3402,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVPApplyReply", Value=3403)]
      kMsgGS2CLPVPApplyReply = 3403,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSPVPCancelApplyRequest", Value=3404)]
      kMsgCL2GSPVPCancelApplyRequest = 3404,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVPCancelApplyReply", Value=3405)]
      kMsgGS2CLPVPCancelApplyReply = 3405,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVPQuitApplyNotice", Value=3406)]
      kMsgGS2CLPVPQuitApplyNotice = 3406,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVPResultNotice", Value=3407)]
      kMsgGS2CLPVPResultNotice = 3407,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSArenaInfoRequest", Value=3408)]
      kMsgCL2GSArenaInfoRequest = 3408,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLArenaInfoReply", Value=3409)]
      kMsgGS2CLArenaInfoReply = 3409,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSArenaUpdateLineupRequest", Value=3410)]
      kMsgCL2GSArenaUpdateLineupRequest = 3410,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLArenaUpdateLineupReply", Value=3411)]
      kMsgGS2CLArenaUpdateLineupReply = 3411,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLArenaAddBattleRecordNotice", Value=3412)]
      kMsgGS2CLArenaAddBattleRecordNotice = 3412,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSArenaUnlockChestRequest", Value=3413)]
      kMsgCL2GSArenaUnlockChestRequest = 3413,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLArenaUnlockChestReply", Value=3414)]
      kMsgGS2CLArenaUnlockChestReply = 3414,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSArenaOpenChestRequest", Value=3415)]
      kMsgCL2GSArenaOpenChestRequest = 3415,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLArenaOpenChestReply", Value=3416)]
      kMsgGS2CLArenaOpenChestReply = 3416,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLArenaAddChestNotice", Value=3417)]
      kMsgGS2CLArenaAddChestNotice = 3417,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSArenaImmediateChestRequest", Value=3418)]
      kMsgCL2GSArenaImmediateChestRequest = 3418,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLArenaImmediateChestReply", Value=3419)]
      kMsgGS2CLArenaImmediateChestReply = 3419,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLArenaRemoveChestNotice", Value=3420)]
      kMsgGS2CLArenaRemoveChestNotice = 3420,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSArenaExtendChestQueueRequest", Value=3421)]
      kMsgCL2GSArenaExtendChestQueueRequest = 3421,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLArenaExtendChestQueueReply", Value=3422)]
      kMsgGS2CLArenaExtendChestQueueReply = 3422,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLArenaUpdateCupNotice", Value=3423)]
      kMsgGS2CLArenaUpdateCupNotice = 3423,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLArenaChestAwardNotice", Value=3424)]
      kMsgGS2CLArenaChestAwardNotice = 3424,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgAS2GSPVPResultNotice", Value=3451)]
      kMsgAS2GSPVPResultNotice = 3451,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgAS2GSPVPCancelApplyNotice", Value=3452)]
      kMsgAS2GSPVPCancelApplyNotice = 3452,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerArenaEnd", Value=3500)]
      kMsgPlayerArenaEnd = 3500,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerCaravanBegin", Value=3501)]
      kMsgPlayerCaravanBegin = 3501,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSCaravanInfoRequest", Value=3502)]
      kMsgCL2GSCaravanInfoRequest = 3502,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLCaravanInfoReply", Value=3503)]
      kMsgGS2CLCaravanInfoReply = 3503,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLCaravanUpdateNotice", Value=3504)]
      kMsgGS2CLCaravanUpdateNotice = 3504,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSCaravanStartEscortRequest", Value=3505)]
      kMsgCL2GSCaravanStartEscortRequest = 3505,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLCaravanStartEscortReply", Value=3506)]
      kMsgGS2CLCaravanStartEscortReply = 3506,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLCaravanAddTargetNotice", Value=3507)]
      kMsgGS2CLCaravanAddTargetNotice = 3507,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLCaravanRemoveTargetNotice", Value=3508)]
      kMsgGS2CLCaravanRemoveTargetNotice = 3508,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSCaravanRobRequest", Value=3509)]
      kMsgCL2GSCaravanRobRequest = 3509,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLCaravanRobReply", Value=3510)]
      kMsgGS2CLCaravanRobReply = 3510,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLCaravanEndNotice", Value=3511)]
      kMsgGS2CLCaravanEndNotice = 3511,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLCaravanBattleResultNotice", Value=3512)]
      kMsgGS2CLCaravanBattleResultNotice = 3512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgAS2GSCaravanUpdateBattleResultNotice", Value=3571)]
      kMsgAS2GSCaravanUpdateBattleResultNotice = 3571,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgAS2GSCaravanRemoveMatchNotice", Value=3572)]
      kMsgAS2GSCaravanRemoveMatchNotice = 3572,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgAS2GSCaravanUpdateEscortEndNotice", Value=3573)]
      kMsgAS2GSCaravanUpdateEscortEndNotice = 3573,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgPlayerCaravanEnd", Value=3600)]
      kMsgPlayerCaravanEnd = 3600,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVEBegin", Value=3601)]
      kMsgGS2CLPVEBegin = 3601,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSPVEDataRequest", Value=3602)]
      kMsgCL2GSPVEDataRequest = 3602,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVEDataReply", Value=3603)]
      kMsgGS2CLPVEDataReply = 3603,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSPVERobRequest", Value=3604)]
      kMsgCL2GSPVERobRequest = 3604,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVERobReply", Value=3605)]
      kMsgGS2CLPVERobReply = 3605,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSPVEResetEnemyRequest", Value=3606)]
      kMsgCL2GSPVEResetEnemyRequest = 3606,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVEResetEnemyReply", Value=3607)]
      kMsgGS2CLPVEResetEnemyReply = 3607,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVEAddEnemyNotice", Value=3608)]
      kMsgGS2CLPVEAddEnemyNotice = 3608,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVEUpdaeEnemyNotice", Value=3609)]
      kMsgGS2CLPVEUpdaeEnemyNotice = 3609,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVERemoveEnemyNotice", Value=3610)]
      kMsgGS2CLPVERemoveEnemyNotice = 3610,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSPVEEnemyViewRequest", Value=3611)]
      kMsgCL2GSPVEEnemyViewRequest = 3611,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVEEnemyViewReply", Value=3612)]
      kMsgGS2CLPVEEnemyViewReply = 3612,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgCL2GSPVEBeginBattleRequest", Value=3613)]
      kMsgCL2GSPVEBeginBattleRequest = 3613,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVEBeginBattleReply", Value=3614)]
      kMsgGS2CLPVEBeginBattleReply = 3614,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVEEndBattleNotice", Value=3615)]
      kMsgGS2CLPVEEndBattleNotice = 3615,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLUpdatePVEInfoNotice", Value=3616)]
      kMsgGS2CLUpdatePVEInfoNotice = 3616,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLUpdatePVEMapEnemiesNotice", Value=3617)]
      kMsgGS2CLUpdatePVEMapEnemiesNotice = 3617,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2CLPVEEnd", Value=3700)]
      kMsgGS2CLPVEEnd = 3700,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2GSViewPlayerPVEInfoRequest", Value=3701)]
      kMsgGS2GSViewPlayerPVEInfoRequest = 3701,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2GSViewPlayerPVEInfoReply", Value=3702)]
      kMsgGS2GSViewPlayerPVEInfoReply = 3702,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2GSUpdatePVERobedRequest", Value=3703)]
      kMsgGS2GSUpdatePVERobedRequest = 3703,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgGS2GSUpdatePVERobedReply", Value=3704)]
      kMsgGS2GSUpdatePVERobedReply = 3704,
            
      [global::ProtoBuf.ProtoEnum(Name=@"kMsgClientEnd", Value=65000)]
      kMsgClientEnd = 65000
    }
  
}