// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Clan.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace ProtoMsg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PbClanBean : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"level")]
        public uint Level { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"exp")]
        public uint Exp { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"symbol")]
        public uint Symbol { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"join_type")]
        public uint JoinType { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"limit_cup")]
        public uint LimitCup { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"placard")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Placard { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9, Name = @"member_num")]
        public uint MemberNum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PbClanMemberBean : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"player_i_d")]
        public ulong PlayerID { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"head")]
        public uint Head { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"head_frame")]
        public uint HeadFrame { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"param")]
        public uint Param { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"title")]
        public uint Title { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"level")]
        public uint Level { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"cup")]
        public uint Cup { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"last_login_time")]
        public long LastLoginTime { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"total_contri_val")]
        public int TotalContriVal { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"previous_rank")]
        public int PreviousRank { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PbClanActionKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"series_id")]
        public uint SeriesId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CS2GS_CLAN_SYN_CLAN_INFO")]
    public partial class MsgCs2gsClanSynClanInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_player_uuid")]
        public long RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"object_player_uuid")]
        public long ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_cup")]
        public int ClanCup { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"clan_bean")]
        public PbClanBean ClanBean { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"notice_cd_time")]
        public int NoticeCdTime { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"last_symbol")]
        public int LastSymbol { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"symbol_left_time")]
        public int SymbolLeftTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CS2GS_CLAN_SYN_MEMBER_INFO")]
    public partial class MsgCs2gsClanSynMemberInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_player_uuid")]
        public long RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"object_player_uuid")]
        public long ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_id")]
        public int ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"member_num")]
        public int MemberNum { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"member_bean")]
        public global::System.Collections.Generic.List<PbClanMemberBean> MemberBeans { get; } = new global::System.Collections.Generic.List<PbClanMemberBean>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CS2GS_CLAN_SYN_CLAN_NAME")]
    public partial class MsgCs2gsClanSynClanName : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClanName { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CS_CLAN_REQ_CLAN_INFO")]
    public partial class MsgGs2csClanReqClanInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CS2GS_CLAN_RSP_CLAN_INFO")]
    public partial class MsgCs2gsClanRspClanInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"clan_id")]
        public uint ClanId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CS_CLAN_REQ_MEMBER_INFO")]
    public partial class MsgGs2csClanReqMemberInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_player_uuid")]
        public long RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_id")]
        public int ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"member_uuid")]
        public long MemberUuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CS2GS_CLAN_RSP_MEMBER_INFO")]
    public partial class MsgCs2gsClanRspMemberInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"request_player_uuid")]
        public long RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"clan_id")]
        public int ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"member_uuid")]
        public long MemberUuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CS_CLAN_REQ_CREATE_CLAN")]
    public partial class MsgGs2csClanReqCreateClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"player_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlayerName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"player_lv")]
        public uint PlayerLv { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"player_cup")]
        public uint PlayerCup { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"clan_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClanName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"clan_symbol")]
        public uint ClanSymbol { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"clan_join_type")]
        public uint ClanJoinType { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"clan_limit_cup")]
        public uint ClanLimitCup { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"clan_placard")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClanPlacard { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CS2GS_CLAN_RSP_CREATE_CLAN")]
    public partial class MsgCs2gsClanRspCreateClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"player_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlayerName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"player_lv")]
        public uint PlayerLv { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"player_cup")]
        public uint PlayerCup { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"clan_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClanName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"clan_symbol")]
        public uint ClanSymbol { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"clan_join_type")]
        public uint ClanJoinType { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"clan_limit_cup")]
        public uint ClanLimitCup { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"clan_placard")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClanPlacard { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"clan_id")]
        public uint ClanId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CS_CLAN_REQ_DISBAND_CLAN")]
    public partial class MsgGs2csClanReqDisbandClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_id")]
        public uint ClanId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CS2GS_CLAN_RSP_DISBAND_CLAN")]
    public partial class MsgCs2gsClanRspDisbandClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_id")]
        public uint ClanId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CS_CLAN_REQ_CHANGE_CLAN_ATTR")]
    public partial class MsgGs2csClanReqChangeClanAttr : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"attr_type")]
        public uint AttrType { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"attr_val")]
        public long AttrVal { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"attr_str")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AttrStr { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CS2GS_CLAN_RSP_CHANGE_CLAN_ATTR")]
    public partial class MsgCs2gsClanRspChangeClanAttr : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"attr_type")]
        public uint AttrType { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"attr_val")]
        public long AttrVal { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"attr_str")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AttrStr { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CS_CLAN_REQ_JOIN_CLAN")]
    public partial class MsgGs2csClanReqJoinClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"player_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlayerName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"player_lv")]
        public uint PlayerLv { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"player_cup")]
        public uint PlayerCup { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"explain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Explain { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CS2GS_CLAN_RSP_JOIN_CLAN")]
    public partial class MsgCs2gsClanRspJoinClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"player_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlayerName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"player_lv")]
        public uint PlayerLv { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"player_cup")]
        public uint PlayerCup { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"explain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Explain { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CS_CLAN_REQ_VERIFIER_JOIN_CLAN")]
    public partial class MsgGs2csClanReqVerifierJoinClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"action_key")]
        public PbClanActionKey ActionKey { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"allow")]
        public bool Allow { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"explain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Explain { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CS2GS_CLAN_RSP_VERIFIER_JOIN_CLAN")]
    public partial class MsgCs2gsClanRspVerifierJoinClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"action_key")]
        public PbClanActionKey ActionKey { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"allow")]
        public bool Allow { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"explain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Explain { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CS_CLAN_REQ_LEAVE_CLAN")]
    public partial class MsgGs2csClanReqLeaveClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"explain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Explain { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CS2GS_CLAN_RSP_LEAVE_CLAN")]
    public partial class MsgCs2gsClanRspLeaveClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"explain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Explain { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CS_CLAN_REQ_CHANGE_LEADER")]
    public partial class MsgGs2csClanReqChangeLeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CS2GS_CLAN_RSP_CHANGE_LEADER")]
    public partial class MsgCs2gsClanRspChangeLeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CS_CLAN_REQ_CHANGE_MEMBER_ATTR")]
    public partial class MsgGs2csClanReqChangeMemberAttr : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"attr_type")]
        public uint AttrType { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"attr_val")]
        public long AttrVal { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CS2GS_CLAN_RSP_CHANGE_MEMBER_ATTR")]
    public partial class MsgCs2gsClanRspChangeMemberAttr : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"attr_type")]
        public uint AttrType { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"attr_val")]
        public long AttrVal { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CS_CLAN_REQ_CHANGE_MEMBER_TITLE")]
    public partial class MsgGs2csClanReqChangeMemberTitle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"new_title")]
        public uint NewTitle { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CS2GS_CLAN_RSP_CHANGE_MEMBER_TITLE")]
    public partial class MsgCs2gsClanRspChangeMemberTitle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"new_title")]
        public uint NewTitle { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CS_CLAN_REQ_SEND_INVITE_NOTICE")]
    public partial class MsgGs2csClanReqSendInviteNotice : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"invite_code")]
        public uint InviteCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CS2GS_CLAN_RSP_SEND_INVITE_NOTICE")]
    public partial class MsgCs2gsClanRspSendInviteNotice : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"error_code")]
        public uint ErrorCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CS_CLAN_REQ_TRANSFER_LEADER")]
    public partial class MsgGs2csClanReqTransferLeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_id")]
        public uint ClanId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CS2GS_CLAN_RSP_TRANSFER_LEADER")]
    public partial class MsgCs2gsClanRspTransferLeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"request_player_uuid")]
        public ulong RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CLAN_EVT_SYN_CREATE_CLAN")]
    public partial class MsgClanEvtSynCreateClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id")]
        public uint ClanId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CLAN_EVT_SYN_DISBAND_CLAN")]
    public partial class MsgClanEvtSynDisbandClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id")]
        public uint ClanId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CLAN_EVT_SYN_CHANGE_CLAN_ATTR")]
    public partial class MsgClanEvtSynChangeClanAttr : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"attr_type")]
        public uint AttrType { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CLAN_EVT_SYN_CHANGE_CLAN_LEADER")]
    public partial class MsgClanEvtSynChangeClanLeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"old_leader_id")]
        public long OldLeaderId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"new_leader_id")]
        public long NewLeaderId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"transfer")]
        public bool Transfer { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CLAN_EVT_SYN_CLAN_LEV_CHANGE")]
    public partial class MsgClanEvtSynClanLevChange : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"old_lv")]
        public int OldLv { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"new_lv")]
        public int NewLv { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CLAN_EVT_SYN_CLAN_EXP_CHANGE")]
    public partial class MsgClanEvtSynClanExpChange : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"new_exp")]
        public int NewExp { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CLAN_EVT_SYN_JOIN_CLAN")]
    public partial class MsgClanEvtSynJoinClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"op_player_id")]
        public long OpPlayerId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"target_player_id")]
        public long TargetPlayerId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CLAN_EVT_SYN_LEAVE_CLAN")]
    public partial class MsgClanEvtSynLeaveClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"op_player_id")]
        public long OpPlayerId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"target_player_id")]
        public long TargetPlayerId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CLAN_EVT_SYN_CHANGE_MEMBER_ATTR")]
    public partial class MsgClanEvtSynChangeMemberAttr : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"player_id")]
        public long PlayerId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"attr_type")]
        public uint AttrType { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CLAN_EVT_SYN_CHANGE_MEMBER_TITLE")]
    public partial class MsgClanEvtSynChangeMemberTitle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"op_player_id")]
        public long OpPlayerId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"target_player_id")]
        public long TargetPlayerId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"new_title")]
        public EClanMemberTitle NewTitle { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_CLAN_SYN_CLAN_INFO")]
    public partial class MsgGs2clClanSynClanInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"object_player_uuid")]
        public long ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_cup")]
        public int ClanCup { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_bean")]
        public PbClanBean ClanBean { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"notice_cd_time")]
        public int NoticeCdTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"last_symbol")]
        public int LastSymbol { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"symbol_left_time")]
        public int SymbolLeftTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_CLAN_SYN_MEMBER_INFO")]
    public partial class MsgGs2clClanSynMemberInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"object_player_uuid")]
        public long ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_id")]
        public int ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"member_num")]
        public int MemberNum { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"member_bean")]
        public global::System.Collections.Generic.List<PbClanMemberBean> MemberBeans { get; } = new global::System.Collections.Generic.List<PbClanMemberBean>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_CLAN_SYN_CLAN_NAME")]
    public partial class MsgGs2clClanSynClanName : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClanName { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_CLAN_REQ_CLAN_INFO")]
    public partial class MsgCl2gsClanReqClanInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_CLAN_RSP_CLAN_INFO")]
    public partial class MsgGs2clClanRspClanInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_id")]
        public uint ClanId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_CLAN_REQ_MEMBER_INFO")]
    public partial class MsgCl2gsClanReqMemberInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_id")]
        public int ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"member_uuid")]
        public long MemberUuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_CLAN_RSP_MEMBER_INFO")]
    public partial class MsgGs2clClanRspMemberInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_id")]
        public int ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"member_uuid")]
        public long MemberUuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_CLAN_REQ_CREATE_CLAN")]
    public partial class MsgCl2gsClanReqCreateClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClanName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_symbol")]
        public uint ClanSymbol { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_join_type")]
        public uint ClanJoinType { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"clan_limit_cup")]
        public uint ClanLimitCup { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"clan_placard")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClanPlacard { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_CLAN_RSP_CREATE_CLAN")]
    public partial class MsgGs2clClanRspCreateClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClanName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_symbol")]
        public uint ClanSymbol { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"clan_join_type")]
        public uint ClanJoinType { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"clan_limit_cup")]
        public uint ClanLimitCup { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"clan_placard")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClanPlacard { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"clan_id")]
        public uint ClanId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_CLAN_REQ_DISBAND_CLAN")]
    public partial class MsgCl2gsClanReqDisbandClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id")]
        public uint ClanId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_CLAN_RSP_DISBAND_CLAN")]
    public partial class MsgGs2clClanRspDisbandClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_id")]
        public uint ClanId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_CLAN_REQ_CHANGE_CLAN_ATTR")]
    public partial class MsgCl2gsClanReqChangeClanAttr : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"attr_type")]
        public uint AttrType { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"attr_val")]
        public long AttrVal { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"attr_str")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AttrStr { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_CLAN_RSP_CHANGE_CLAN_ATTR")]
    public partial class MsgGs2clClanRspChangeClanAttr : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"attr_type")]
        public uint AttrType { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"attr_val")]
        public long AttrVal { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"attr_str")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AttrStr { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_CLAN_REQ_JOIN_CLAN")]
    public partial class MsgCl2gsClanReqJoinClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"explain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Explain { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_CLAN_RSP_JOIN_CLAN")]
    public partial class MsgGs2clClanRspJoinClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"explain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Explain { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_CLAN_REQ_VERIFIER_JOIN_CLAN")]
    public partial class MsgCl2gsClanReqVerifierJoinClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"action_key")]
        public PbClanActionKey ActionKey { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"allow")]
        public bool Allow { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"explain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Explain { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_CLAN_RSP_VERIFIER_JOIN_CLAN")]
    public partial class MsgGs2clClanRspVerifierJoinClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"action_key")]
        public PbClanActionKey ActionKey { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"allow")]
        public bool Allow { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"explain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Explain { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_CLAN_REQ_LEAVE_CLAN")]
    public partial class MsgCl2gsClanReqLeaveClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"explain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Explain { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_CLAN_RSP_LEAVE_CLAN")]
    public partial class MsgGs2clClanRspLeaveClan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"explain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Explain { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_CLAN_REQ_CHANGE_LEADER")]
    public partial class MsgCl2gsClanReqChangeLeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_CLAN_RSP_CHANGE_LEADER")]
    public partial class MsgGs2clClanRspChangeLeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_CLAN_REQ_CHANGE_MEMBER_TITLE")]
    public partial class MsgCl2gsClanReqChangeMemberTitle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"new_title")]
        public uint NewTitle { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_CLAN_RSP_CHANGE_MEMBER_TITLE")]
    public partial class MsgGs2clClanRspChangeMemberTitle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_id")]
        public uint ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"new_title")]
        public uint NewTitle { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_CLAN_REQ_SEND_INVITE_NOTICE")]
    public partial class MsgCl2gsClanReqSendInviteNotice : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"invite_code")]
        public uint InviteCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_CLAN_RSP_SEND_INVITE_NOTICE")]
    public partial class MsgGs2clClanRspSendInviteNotice : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public uint ErrorCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_CLAN_REQ_TRANSFER_LEADER")]
    public partial class MsgCl2gsClanReqTransferLeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_CLAN_RSP_TRANSFER_LEADER")]
    public partial class MsgGs2clClanRspTransferLeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"object_player_uuid")]
        public ulong ObjectPlayerUuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_CLAN_REQ_CLAN_LIST")]
    public partial class MsgCl2gsClanReqClanList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint pageIndex { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_CLAN_RSP_CLAN_LIST")]
    public partial class MsgGs2clClanRspClanList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clan_bean")]
        public global::System.Collections.Generic.List<PbClanBean> ClanBeans { get; } = new global::System.Collections.Generic.List<PbClanBean>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CS_CLAN_REQ_CLAN_LIST")]
    public partial class MsgGs2csClanReqClanList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint pageIndex { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CS2GS_CLAN_RSP_CLAN_LIST")]
    public partial class MsgCs2gsClanRspClanList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
        public int ErrorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"request_player_uuid")]
        public long RequestPlayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"clan_bean")]
        public global::System.Collections.Generic.List<PbClanBean> ClanBeans { get; } = new global::System.Collections.Generic.List<PbClanBean>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum EClanMemberTitle
    {
        [global::ProtoBuf.ProtoEnum(Name = @"eCMT_NOTMEMBER")]
        eCMTNOTMEMBER = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"eCMT_COMMON")]
        eCMTCOMMON = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"eCMT_ELDER")]
        eCMTELDER = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"eCMT_LEADER")]
        eCMTLEADER = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EClanErrorCode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_NO_ERROR")]
        eCECNOERROR = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_UNKNOWN_ERROR")]
        eCECUNKNOWNERROR = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_CC_IN_CLAN")]
        eCECCCINCLAN = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_CC_NAME")]
        eCECCCNAME = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_CC_JOIN_TYPE")]
        eCECCCJOINTYPE = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_CC_PLACARD")]
        eCECCCPLACARD = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_CC_NOT_CLAN_BUILDING")]
        eCECCCNOTCLANBUILDING = 15,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_DC_NO_POWER")]
        eCECDCNOPOWER = 101,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_DC_MEMBER_NUM")]
        eCECDCMEMBERNUM = 102,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_JC_NO_POWER")]
        eCECJCNOPOWER = 201,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_JC_APPLY_CUP_LIMIT")]
        eCECJCAPPLYCUPLIMIT = 202,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_JC_HAVE_CLAN")]
        eCECJCHAVECLAN = 203,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_JC_MEMBER_FULL")]
        eCECJCMEMBERFULL = 204,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_KM_NO_POWER")]
        eCECKMNOPOWER = 301,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_CL_NO_POWER")]
        eCECCLNOPOWER = 401,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_CL_DST_NOT_IN_CLAN")]
        eCECCLDSTNOTINCLAN = 402,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_CL_DST_ACTIVE_LEADER")]
        eCECCLDSTACTIVELEADER = 403,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_CL_CUP_RANK_NOT_ENOUGH")]
        eCECCLCUPRANKNOTENOUGH = 404,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_CT_NO_POWER")]
        eCECCTNOPOWER = 501,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_CT_DST_NOT_IN_CLAN")]
        eCECCTDSTNOTINCLAN = 502,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_CT_NO_CHANGE_CLAN_NAME_POWER")]
        eCECCTNOCHANGECLANNAMEPOWER = 601,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_CT_NO_CHANGE_CLAN_SYMBOL_POWER")]
        eCECCTNOCHANGECLANSYMBOLPOWER = 610,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_CT_NO_CHANGE_CLAN_JOIN_TYPE_POWER")]
        eCECCTNOCHANGECLANJOINTYPEPOWER = 620,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_CT_NO_CHANGE_CLAN_LIMIT_CUP_POWER")]
        eCECCTNOCHANGECLANLIMITCUPPOWER = 630,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_CT_NO_CHANGE_CLAN_PLACARD_POWER")]
        eCECCTNOCHANGECLANPLACARDPOWER = 640,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_RENAME_NO_POWER")]
        eCECRENAMENOPOWER = 701,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_RENAME_DST_NOT_IN_CLAN")]
        eCECRENAMEDSTNOTINCLAN = 702,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_RENAME_ERROR_NAME")]
        eCECRENAMEERRORNAME = 703,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_RENAME_GEM")]
        eCECRENAMEGEM = 704,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_AT_NOT_FIND")]
        eCECATNOTFIND = 100001,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_AT_HAVE_CLAN")]
        eCECATHAVECLAN = 100101,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_AT_CANNOT_APPLY")]
        eCECATCANNOTAPPLY = 100102,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_AT_MEMBER_FULL")]
        eCECATMEMBERFULL = 100103,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_AT_NO_VERIFIER_POWER")]
        eCECATNOVERIFIERPOWER = 100104,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_AT_FREQUENTLY_APPLY")]
        eCECATFREQUENTLYAPPLY = 100105,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_DB_RECORDSET_NULL")]
        eCECDBRECORDSETNULL = 100106,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_DB_NO_RECORD")]
        eCECDBNORECORD = 100107,
        [global::ProtoBuf.ProtoEnum(Name = @"eCEC_DB_NO_MEMORY")]
        eCECDBNOMEMORY = 100108,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
