// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Test.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace ProtoMsg
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PosCoord : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public float X { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"y")]
        public float Y { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"z")]
        public float Z { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ToyInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"toy_id")]
        public long ToyId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"toy_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ToyName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"toy_lv")]
        public int ToyLv { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"hp")]
        public int Hp { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"mp")]
        public int Mp { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"pos")]
        public PosCoord Pos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BuffInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"buff_id")]
        public int BuffId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ref_id")]
        public int RefId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"param", IsPacked = true)]
        public int[] Params { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_MAP_SYN_TOY_ADD")]
    public partial class MsgGs2clMapSynToyAdd : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"toy_info")]
        public global::System.Collections.Generic.List<ToyInfo> ToyInfoes { get; } = new global::System.Collections.Generic.List<ToyInfo>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_MAP_SYN_TOY_DEL")]
    public partial class MsgGs2clMapSynToyDel : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"toy_id", IsPacked = true)]
        public long[] ToyIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_BATTLE_REQ_CAST")]
    public partial class MsgCl2gsBattleReqCast : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"spell_id")]
        public int SpellId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"target_toy_id")]
        public long TargetToyId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"target_pos")]
        public PosCoord TargetPos { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_BATTLE_RSP_CAST")]
    public partial class MsgGs2clBattleRspCast : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"err_code")]
        public EnumGeneralErr ErrCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"spell_id")]
        public int SpellId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"target_toy_id")]
        public long TargetToyId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"target_pos")]
        public PosCoord TargetPos { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_BATTLE_REQ_LAUNCH")]
    public partial class MsgCl2gsBattleReqLaunch : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target_toy_id")]
        public long TargetToyId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_BATTLE_RSP_LAUNCH")]
    public partial class MsgGs2clBattleRspLaunch : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"err_code")]
        public EnumGeneralErr ErrCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"target_toy_id")]
        public long TargetToyId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_BATTLE_SYN_BEGIN")]
    public partial class MsgGs2clBattleSynBegin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"battle_id")]
        public long BattleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"atk_toy_id")]
        public long AtkToyId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"def_toy_id")]
        public long DefToyId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_BATTLE_SYN_END")]
    public partial class MsgGs2clBattleSynEnd : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"battle_id")]
        public long BattleId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_BATTLE_SYN_JOIN")]
    public partial class MsgGs2clBattleSynJoin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"battle_id")]
        public long BattleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"toy_id")]
        public long ToyId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_BATTLE_SYN_ESCAPE")]
    public partial class MsgGs2clBattleSynEscape : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"battle_id")]
        public long BattleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"toy_id")]
        public long ToyId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_BATTLE_SYN_SPELL_CHANT")]
    public partial class MsgGs2clBattleSynSpellChant : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"toy_id")]
        public long ToyId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"toy_cur_pos")]
        public PosCoord ToyCurPos { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"toy_cur_rotate")]
        public float ToyCurRotate { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"spell_id")]
        public int SpellId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"spell_lv")]
        public int SpellLv { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_BATTLE_SYN_SPELL_CAST")]
    public partial class MsgGs2clBattleSynSpellCast : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"toy_id")]
        public long ToyId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"toy_cur_pos")]
        public PosCoord ToyCurPos { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"toy_cur_rotate")]
        public float ToyCurRotate { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"cast_type")]
        public EnumCastType CastType { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"spell_id")]
        public int SpellId { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"spell_lv")]
        public int SpellLv { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"spell_param", IsPacked = true)]
        public int[] SpellParams { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"target_toy_id", IsPacked = true)]
        public long[] TargetToyIds { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"target_pos")]
        public PosCoord TargetPos { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_BATTLE_SYN_ATTR_CHARGE")]
    public partial class MsgGs2clBattleSynAttrCharge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"toy_id")]
        public long ToyId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"from_toy_id")]
        public long FromToyId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"from_spell_id")]
        public int FromSpellId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"from_spell_pos")]
        public PosCoord FromSpellPos { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"delta_hp")]
        public int DeltaHp { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"delta_mp")]
        public int DeltaMp { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"effect_type")]
        public EnumBattleEffectType EffectType { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"final_pos")]
        public PosCoord FinalPos { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"final_rotate")]
        public float FinalRotate { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_BATTLE_SYN_BUFF_ADD")]
    public partial class MsgGs2clBattleSynBuffAdd : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"toy_id")]
        public long ToyId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"buff_id")]
        public int BuffId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"buff_sn")]
        public int BuffSn { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"buff_param", IsPacked = true)]
        public int[] BuffParams { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"time_left")]
        public int TimeLeft { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_BATTLE_SYN_BUFF_LOST")]
    public partial class MsgGs2clBattleSynBuffLost : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"toy_id")]
        public long ToyId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"buff_id")]
        public int BuffId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"buff_sn")]
        public int BuffSn { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_PLAYER_RPT_MOVE")]
    public partial class MsgCl2gsPlayerRptMove : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cur_pos")]
        public PosCoord CurPos { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"dest_pos")]
        public PosCoord DestPos { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"cur_time")]
        public long CurTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"arrive_time")]
        public long ArriveTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"match_speed")]
        public float MatchSpeed { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"dest_final_pos")]
        public PosCoord DestFinalPos { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"path_id")]
        public int PathId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_PLAYER_SYN_MOVE")]
    public partial class MsgGs2clPlayerSynMove : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"toy_id")]
        public long ToyId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"cur_pos")]
        public PosCoord CurPos { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"dest_pos")]
        public PosCoord DestPos { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"cur_time")]
        public long CurTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"arrive_time")]
        public long ArriveTime { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"match_speed")]
        public float MatchSpeed { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"dest_final_pos")]
        public PosCoord DestFinalPos { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"path_id")]
        public int PathId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_KD2GS_MAP_SYN_TOY_ADD")]
    public partial class MsgKd2gsMapSynToyAdd : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"toy_info")]
        public global::System.Collections.Generic.List<ToyInfo> ToyInfoes { get; } = new global::System.Collections.Generic.List<ToyInfo>();

        [global::ProtoBuf.ProtoMember(2, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_KD2GS_MAP_SYN_TOY_DEL")]
    public partial class MsgKd2gsMapSynToyDel : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"toy_id", IsPacked = true)]
        public long[] ToyIds { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2KD_BATTLE_REQ_CAST")]
    public partial class MsgGs2kdBattleReqCast : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"spell_id")]
        public int SpellId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"target_toy_id")]
        public long TargetToyId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"target_pos")]
        public PosCoord TargetPos { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_KD2GS_BATTLE_RSP_CAST")]
    public partial class MsgKd2gsBattleRspCast : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"err_code")]
        public EnumGeneralErr ErrCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"spell_id")]
        public int SpellId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"target_toy_id")]
        public long TargetToyId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"target_pos")]
        public PosCoord TargetPos { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2KD_BATTLE_REQ_LAUNCH")]
    public partial class MsgGs2kdBattleReqLaunch : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target_toy_id")]
        public long TargetToyId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_KD2GS_BATTLE_RSP_LAUNCH")]
    public partial class MsgKd2gsBattleRspLaunch : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"err_code")]
        public EnumGeneralErr ErrCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"target_toy_id")]
        public long TargetToyId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2KD_BATTLE_SYN_BEGIN")]
    public partial class MsgGs2kdBattleSynBegin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"battle_id")]
        public long BattleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"atk_toy_id")]
        public long AtkToyId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"def_toy_id")]
        public long DefToyId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_KD2GS_BATTLE_SYN_END")]
    public partial class MsgKd2gsBattleSynEnd : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"battle_id")]
        public long BattleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_KD2GS_BATTLE_SYN_JOIN")]
    public partial class MsgKd2gsBattleSynJoin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"battle_id")]
        public long BattleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"toy_id")]
        public long ToyId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_KD2GS_BATTLE_SYN_ESCAPE")]
    public partial class MsgKd2gsBattleSynEscape : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"battle_id")]
        public long BattleId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"toy_id")]
        public long ToyId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_KD2GS_BATTLE_SYN_SPELL_CHANT")]
    public partial class MsgKd2gsBattleSynSpellChant : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"toy_id")]
        public long ToyId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"toy_cur_pos")]
        public PosCoord ToyCurPos { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"toy_cur_rotate")]
        public float ToyCurRotate { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"spell_id")]
        public int SpellId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"spell_lv")]
        public int SpellLv { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_KD2GS_BATTLE_SYN_SPELL_CAST")]
    public partial class MsgKd2gsBattleSynSpellCast : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"toy_id")]
        public long ToyId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"toy_cur_pos")]
        public PosCoord ToyCurPos { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"toy_cur_rotate")]
        public float ToyCurRotate { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"cast_type")]
        public EnumCastType CastType { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"spell_id")]
        public int SpellId { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"spell_lv")]
        public int SpellLv { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"spell_param", IsPacked = true)]
        public int[] SpellParams { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"target_toy_id", IsPacked = true)]
        public long[] TargetToyIds { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"target_pos")]
        public PosCoord TargetPos { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_KD2GS_BATTLE_SYN_ATTR_CHARGE")]
    public partial class MsgKd2gsBattleSynAttrCharge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"toy_id")]
        public long ToyId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"from_toy_id")]
        public long FromToyId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"from_spell_id")]
        public int FromSpellId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"from_spell_pos")]
        public PosCoord FromSpellPos { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"delta_hp")]
        public int DeltaHp { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"delta_mp")]
        public int DeltaMp { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"effect_type")]
        public EnumBattleEffectType EffectType { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"final_pos")]
        public PosCoord FinalPos { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"final_rotate")]
        public float FinalRotate { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_KD2GS_BATTLE_SYN_BUFF_ADD")]
    public partial class MsgKd2gsBattleSynBuffAdd : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"toy_id")]
        public long ToyId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"buff_id")]
        public int BuffId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"buff_sn")]
        public int BuffSn { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"buff_param", IsPacked = true)]
        public int[] BuffParams { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"time_left")]
        public int TimeLeft { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_KD2GS_BATTLE_SYN_BUFF_LOST")]
    public partial class MsgKd2gsBattleSynBuffLost : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"toy_id")]
        public long ToyId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"buff_id")]
        public int BuffId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"buff_sn")]
        public int BuffSn { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KingdomMapCacheData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cached_data")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CachedData { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_P_KINGDOM_MAP_SYN_CACHE")]
    public partial class MsgPKingdomMapSynCache : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public ulong Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"cache_data")]
        public KingdomMapCacheData CacheData { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_BATTLE_MAP_REQ_ENTER")]
    public partial class MsgCl2gsBattleMapReqEnter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_BATTLE_MAP_RSP_ENTER")]
    public partial class MsgGs2clBattleMapRspEnter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"err_code")]
        public EnumGeneralErr ErrCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2KD_BATTLE_MAP_REQ_ENTER")]
    public partial class MsgGs2kdBattleMapReqEnter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_KD2GS_BATTLE_MAP_RSP_ENTER")]
    public partial class MsgKd2gsBattleMapRspEnter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"err_code")]
        public EnumGeneralErr ErrCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_BATTLE_MAP_REQ_TIME_SYN")]
    public partial class MsgCl2gsBattleMapReqTimeSyn : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_BATTLE_MAP_RSP_TIME_SYN")]
    public partial class MsgGs2clBattleMapRspTimeSyn : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"err_code")]
        public EnumGeneralErr ErrCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long timeSec { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long timeMilliSec { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2KD_BATTLE_MAP_REQ_PLAYER_DISCONNECT")]
    public partial class MsgGs2kdBattleMapReqPlayerDisconnect : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public long Uuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum EnumGeneralErr
    {
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_OK")]
        eKINGDOMOK = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_UNKNOWN")]
        eKINGDOMUNKNOWN = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EnumCastState
    {
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_NONE")]
        eKINGDOMNONE = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_BEGIN")]
        eKINGDOMBEGIN = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_READY")]
        eKINGDOMREADY = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_CHANT")]
        eKINGDOMCHANT = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_CAST")]
        eKINGDOMCAST = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_STIFF")]
        eKINGDOMSTIFF = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_END")]
        eKINGDOMEND = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EnumCastType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_INITIATIVE")]
        eKINGDOMINITIATIVE = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_PASSIVE")]
        eKINGDOMPASSIVE = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_DIRECT")]
        eKINGDOMDIRECT = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EnumBattleEffectType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_NORMAL")]
        eKINGDOMNORMAL = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_LOST")]
        eKINGDOMLOST = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_CRITICAL")]
        eKINGDOMCRITICAL = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_COMBO")]
        eKINGDOMCOMBO = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_BLOCK")]
        eKINGDOMBLOCK = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_DODGE")]
        eKINGDOMDODGE = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_RUSH")]
        eKINGDOMRUSH = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_SHOCK")]
        eKINGDOMSHOCK = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_KNOCK_OFF")]
        eKINGDOMKNOCKOFF = 8,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EnumBuffType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_RECOVER")]
        eKINGDOMRECOVER = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"eKINGDOM_STUN")]
        eKINGDOMSTUN = 1,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
